---
title: "histocat analysis"
author: "Nils Eling"
date: "10/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Here, will will perform an interaction analysis using the `testInteractions`
function from the `imcRtools` package. 

```{r load-data, eval = TRUE}
library(imcRtools)
library(S4Vectors)

cur_graph <- read.csv("/Volumes/sh_thoch/Git/MelanomaIMC/data/full_data/rna/cpout/Object relationships.csv")
sce <- readRDS("/Volumes/sh_thoch/Git/MelanomaIMC/data/data_for_analysis/sce_RNA.rds")

cur_id <- paste0(sce$ImageNumber, "_", sce$CellNumber)
cur_from <- paste0(cur_graph$First.Image.Number, "_", cur_graph$First.Object.Number)
cur_to <- paste0(cur_graph$Second.Image.Number, "_", cur_graph$Second.Object.Number)

cur_sh <- SelfHits(from = match(cur_from, cur_id),
                   to = match(cur_to, cur_id), 
                   nnode = ncol(sce))
colPair(sce, "neighborhood") <- cur_sh
```

Now we loop through the chemokines, rename the cell-types and perform interaction
testing.

```{r interaction-testing, eval=TRUE}
library(BiocParallel)
chemokine_list <- c("CCL4", "CCL18", "CXCL8", "CXCL10", "CXCL12", "CXCL13", "CCL2", 
                    "CCL22", "CXCL9", "CCL8", "CCL19")

interaction_list <- bplapply(chemokine_list,
                             function(x){
                                 cur_sce <- sce
                                 colData(cur_sce) <- NULL
                                 cur_celltype <- sce$celltype
                                 cur_celltype[sce[[x]] == 1] <- x
                                 cur_sce$celltype <- cur_celltype
                                 cur_sce$ImageNumber <- sce$ImageNumber
                                 
                                 cur_interaction <- testInteractions(cur_sce,
                                                        group_by = "ImageNumber",
                                                        label = "celltype",
                                                        colPairName = "neighborhood")
                                 return(cur_interaction)
                             }, BPPARAM = MulticoreParam())

saveRDS(interaction_list, "~/Desktop/interaction_list.rds")
```

## Visualize results

Now, we will average the significance value across all images.

```{r generate-plots, fig.width=30, fig.height=20, message=FALSE}
library(tidyverse)
interaction_list <- readRDS("~/Desktop/interaction_list.rds")
chemokine_list <- c("CCL4", "CCL18", "CXCL8", "CXCL10", "CXCL12", "CXCL13", "CCL2", 
                    "CCL22", "CXCL9", "CCL8", "CCL19")

library(cowplot)
cur_plots <- mapply(function(x, name){
    cur_out <- x %>% as_tibble() %>%
        group_by(from_label, to_label) %>%
        summarize(mean_sig = mean(sigval, na.rm = TRUE))
    
    cur_plot <- ggplot(cur_out) + 
        geom_tile(aes(from_label, to_label, fill = mean_sig)) +
        scale_fill_gradient2(low = "dark blue", mid = "white", high = "dark red") +
        theme(axis.text.x = element_text(angle = 45, hjust = 1),
              text = element_text(size=20)) + ggtitle(name)
    
    return(cur_plot)
}, interaction_list, chemokine_list, SIMPLIFY = FALSE)

plot_grid(plotlist = cur_plots)
```

Finally, we visualize only the chemokines.

```{r viz-chemokine-specific}
cur_list <- mapply(function(x, name){
    cur_out <- x %>% as_tibble() %>%
        group_by(from_label, to_label) %>%
        summarize(mean_sig = mean(sigval, na.rm = TRUE))
    return(cur_out %>% filter(from_label == sym(name)))
}, interaction_list, chemokine_list, SIMPLIFY = FALSE)

cur_df <- do.call("rbind", cur_list)

cur_df %>% 
    filter(!to_label %in% chemokine_list) %>%
    ggplot() + 
        geom_tile(aes(from_label, as.character(to_label), fill = mean_sig)) +
        scale_fill_gradient2(low = "dark blue", mid = "white", high = "dark red",
                             limits = c(-1, 1)) +
        theme(axis.text.x = element_text(angle = 45, hjust = 1),
                text = element_text(size=20)) + ggtitle("Celltype")

cur_df %>% 
    filter(to_label %in% chemokine_list) %>%
    ggplot() + 
        geom_tile(aes(from_label, as.character(to_label), fill = mean_sig)) +
        scale_fill_gradient2(low = "dark blue", mid = "white", high = "dark red",
                             limits = c(-1, 1)) +
        theme(axis.text.x = element_text(angle = 45, hjust = 1),
                text = element_text(size=20)) + ggtitle("Chemokines")
```


