---
title: "Read features from masks"
author: "Nils Eling"
date: "9/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Here, I will read in features from masks using cytomapper and compare this 
against the results of REDSEA.

```{r read-data, eval = FALSE}
library(cytomapper)

all_images <- loadImages("/Volumes/bbvolume/server_homes/thoch/Git/MelanomaIMC/data/full_data/rna/cpout/",
                         pattern = "spillcor.tiff", on_disk = TRUE, h5FilesPath = "~/Desktop/cytomapper_h5/images/", as.is = TRUE)
REDSEA_masks <- loadImages("~/Desktop/REDSEA_masks/",
                         pattern = "cellmask.tiff", on_disk = TRUE, h5FilesPath = "~/Desktop/cytomapper_h5/masks/", as.is = TRUE)

mcols(all_images) <- mcols(REDSEA_masks) <- DataFrame(ImageId = sub("_full_spillcor", "", names(all_images)))

cur_metals <- read.csv("/Volumes/bbvolume/server_homes/thoch/Git/MelanomaIMC/data/full_data/rna/tiffs/20190731_ZTMA256.1_slide2_TH_s1_p14_r1_a1_ac_full.csv", header = FALSE)
cur_panel <- read.csv("/Volumes/bbvolume/server_homes/thoch/Git/MelanomaIMC/data/full_data/rna/config/melanoma_1.06_RNA.csv", header = TRUE)

cur_panel <- cur_panel[match(cur_metals$V1, cur_panel$Metal.Tag),]

channelNames(all_images) <- cur_panel$Target

saveRDS(all_images, "~/Desktop/cytomapper_h5/all_images.rds")
saveRDS(REDSEA_masks, "~/Desktop/cytomapper_h5/REDSEA_masks.rds")
```

Now, we'll measure the expression of cells.

```{r measureObject}
library(BiocParallel)
sce <- measureObjects(mask = all_masks, image = all_images, img_id = "ImageId",
                      BPPARAM = BiocParallel::MulticoreParam())

final_sce <- readRDS("~/Desktop/REDSEA_test/sce_RNA.rds")

# Remove extra "cells"
cur_image_meta <- read.csv("/Volumes/bbvolume/server_homes/thoch/Git/MelanomaIMC/data/full_data/rna/cpout/Image.csv")
cur_image_meta <- cur_image_meta[,c("ImageNumber", "FileName_CellImage")]
cur_image_meta$ImageId <- gsub("_ilastik_s2_Probabilities_equalized_cellmask.tiff", "", 
                               cur_image_meta$FileName_CellImage)

colData(final_sce)$ImageId <-  cur_image_meta$ImageId[final_sce$ImageNumber]

colnames(sce) <- paste(sce$ImageId, sce$object_id)
sce <- sce[,colnames(sce) %in% paste(final_sce$ImageId, final_sce$CellNumber)]
colnames(final_sce) <- paste(final_sce$ImageId, final_sce$CellNumber)

final_subset <- final_sce[,colnames(sce)]

library(ggplot2)
ggplot(data.frame(GLUT1_full = counts(final_subset)["GLUT1",],
                  GLUT1_READSEA_noncorrected = counts(sce)["Glucose Transporter GLUT1",])) +
    geom_hex(aes(asinh(GLUT1_full), asinh(GLUT1_READSEA_noncorrected))) + coord_fixed() +
    geom_abline(slope = 1, intercept = 0, color = "red")

ggplot(data.frame(Vim_full = counts(final_subset)["Vimentin",],
                  Vim_READSEA_noncorrected = counts(sce)["Vimentin",])) +
    geom_hex(aes(asinh(Vim_full), asinh(Vim_READSEA_noncorrected))) + coord_fixed() +
    geom_abline(slope = 1, intercept = 0, color = "red")

saveRDS(sce, "~/Desktop/REDSEA_test/sce_cytomapper_eval.rds")
```