---
title: "Cluster images by celltypes"
author: "Daniel"
date: "09.04.2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

# Load libraries

First, we will load the libraries needed for this part of the analysis.

```{r load-libraries, message=FALSE}
sapply(list.files("~/bbvolume/Git/imcRtools/R/", full.names = TRUE), source)
sapply(list.files("~/bbvolume/Git/ZTMA256_protein_data/code/helper_functions/", full.names = TRUE), source)
library(data.table)
library(S4Vectors)
library(SingleCellExperiment)
library(devtools)
library(ggplot2)
library(tidyverse)
library(cba)
library(ComplexHeatmap)
```

# Read the data

```{r load data}
sce = readRDS(file = "data/sce_protein.rds")

colour_vector <- readRDS("~/bbvolume/Git/ZTMA256_protein_data/data/colour_vector.rds")

image_mat <- as.data.frame(read.csv(file = "~/bbvolume/Data/Melanoma/12plex/protein/cpout/Image.csv",stringsAsFactors = FALSE))
# here we get the imagesize from the image metadata
im_size <- (image_mat$Height_cellmask * image_mat$Width_cellmask)/1000000
```




plot per image the fraction of cytotoxic T cells that sit next to a tumor cell per tumor cell colored by infiltration

the red line in the plot marks images that have one or more cytotoxic T cells sitting next to a tumor cells per 10 tumor cells



```{r barplot Tcell score sorted with Death, fig.height=10, fig.width=15}
cur_df <- data.frame(E_I_D = sce$E_I_D,
                     ImageNumber = sce$ImageNumber,
                     celltype = sce$celltype,
                     Tcell_score = sce$Tcell_score,
                     infiltration = sce$infiltration)

cur_df <- reshape2::dcast(cur_df,formula = "ImageNumber + Tcell_score  ~ celltype")
cur_df <- as.tibble(cur_df)


cur_df$image_size <- im_size[cur_df$ImageNumber]


# calculate the density of Tcytotoxic cells
cur_df <- cur_df %>%
  mutate(Tcytotoxic_density = round(Tcytotoxic/image_size))

matrixrownames <- as.character(cur_df$ImageNumber)

m <- as.matrix(cur_df$Tcytotoxic_density)
rownames(m) <- matrixrownames
m <- m[order(m[,1]),]

# construct color vector for Tcell score
count_vec <- as.vector(m)
length(count_vec[count_vec<40])

Tcell_score_col <- c(rep("red",length(count_vec[count_vec<=40])),
                         rep("orange",length(count_vec[which(count_vec <100 & count_vec > 40)])),
                         rep("lightgreen",length(count_vec[which(count_vec <400 & count_vec > 100)])),
                         rep("darkgreen",length(count_vec[count_vec>400])))

ha <- rowAnnotation(cell_composition = anno_barplot(m,gp=gpar(fill=Tcell_score_col),bar_width = 1,height = unit(30,"cm"),width = unit(15,"cm"),show_row_names =FALSE))

# now we sort the patient meta data
patient_meta <- as.data.table(metadata(sce))
patient_meta <- unique(patient_meta %>%
  select(ImageNumber ,Response_at_12m  ,Mutation , MM_location , Date_death , Adjuvant))


mrownames <- patient_meta$ImageNumber
patient_meta <- as.matrix(patient_meta)

rownames(patient_meta) <- as.character(mrownames)
patient_meta <- patient_meta[names(m),]

# heatmap consisting of the patient_IDs. one color per patient
h1 = Heatmap(patient_meta[,"Date_death"], width = unit(0.5, "cm"), 
             height = unit(30, "cm"),
             show_heatmap_legend = TRUE,heatmap_legend_param = list(title = "Date death"),show_row_names = FALSE,
             column_labels = "Date death",right_annotation =  ha)


ht = grid.grabExpr(draw( h1))
grid.newpage()
pushViewport(viewport(angle = 270))
grid.draw(ht)
```

```{r barplot Tcell score sorted with death for BlockID, fig.height=15, fig.width=15, message=FALSE}
set.seed(436)
cur_df <- data.frame(E_I_D = sce$E_I_D,
                     BlockID = sce$BlockID,
                     celltype = sce$celltype,
                     Tcell_score = sce$Tcell_score_per_BlockID,
                     infiltration = sce$infiltration,
                     MM_location = sce$MM_location)

cur_df <- cur_df[which(cur_df$MM_location != ""),]

cur_df <- reshape2::dcast(cur_df,formula = "BlockID + Tcell_score  ~ celltype", fun.aggregate = length)
cur_df <- as.tibble(cur_df)

# create named vector with ImageNumber and BlockID
block_images <- data.frame(ImageNumber = sce$ImageNumber,
                           BlockID = sce$BlockID)
block_images <- unique(block_images)
block_vec <- block_images$BlockID


block_size <- data.frame(ImageNumber = 1:length(im_size),
                         image_size = im_size)
block_size$BlockID <- block_vec

block_size <- block_size %>%
  group_by(BlockID) %>%
  mutate(Blocksize = sum(image_size))

# remove unwanted information for merging
block_size <- unique(block_size %>%
  select(BlockID, Blocksize))
# add info to cur_df
cur_df <- left_join(x = cur_df,y = block_size,"BlockID")

# calculate the density of Tcytotoxic cells
cur_df <- cur_df %>%
  mutate(Tcytotoxic_density = round(Tcytotoxic/Blocksize)) 

matrixrownames <- as.character(cur_df$BlockID)

m <- as.matrix(cur_df$Tcytotoxic_density)
rownames(m) <- matrixrownames
m <- m[order(m[,1]),]

# construct color vector for Tcell score
count_vec <- as.vector(m)


Tcell_score_col <- c(rep("red",length(count_vec[count_vec<=40])),
                         rep("orange",length(count_vec[which(count_vec <100 & count_vec > 40)])),
                         rep("lightgreen",length(count_vec[which(count_vec <400 & count_vec > 100)])),
                         rep("darkgreen",length(count_vec[count_vec>400])))

ha <- rowAnnotation(Tcells_per_mm2 = anno_barplot(m,gp=gpar(fill=Tcell_score_col),bar_width = 1,height = unit(30,"cm"),width = unit(15,"cm"),show_row_names =FALSE,ylab = "test"))

patient_meta <- as.data.table(metadata(sce))
patient_meta <- unique(patient_meta %>%
                         filter(BlockID %in% names(m)) %>%
                       select(BlockID ,Response_at_12m  ,Mutation , MM_location , Date_death , Adjuvant, Treatment_after_surgery, E_I_D))


mrownames <- patient_meta$BlockID
patient_meta <- as.matrix(patient_meta)

rownames(patient_meta) <- as.character(mrownames)
patient_meta <- patient_meta[names(m),]


# heatmap consisting of the patient_IDs. one color per patient
h1 = Heatmap(patient_meta[,"Date_death"], width = unit(0.5, "cm"), 
             height = unit(30, "cm"),
             show_heatmap_legend = TRUE,heatmap_legend_param = list(title = "Date death"),show_row_names = FALSE,
             column_labels = "Date death",right_annotation =  ha)
h2 = Heatmap(patient_meta[,"Mutation"], width = unit(0.5, "cm"), 
             height = unit(30, "cm"),
             show_heatmap_legend = TRUE,heatmap_legend_param = list(title = "Mutation"),show_row_names = FALSE,
             column_labels = "Mutation")
h4 = Heatmap(patient_meta[,"Treatment_after_surgery"], width = unit(0.5, "cm"), 
             height = unit(30, "cm"),
             show_heatmap_legend = TRUE,heatmap_legend_param = list(title = "Treatment_after_surgery"),show_row_names = FALSE,
             column_labels = "Treatment_after_surgery")
h5 = Heatmap(patient_meta[,"MM_location"], width = unit(0.5, "cm"), 
             height = unit(30, "cm"),
             show_heatmap_legend = TRUE,heatmap_legend_param = list(title = "MM_location"),show_row_names = FALSE,
             column_labels = "MM_location")
h6 = Heatmap(patient_meta[,"Adjuvant"], width = unit(0.5, "cm"), 
             height = unit(30, "cm"),
             show_heatmap_legend = TRUE,heatmap_legend_param = list(title = "Adjuvant"),show_row_names = FALSE,
             column_labels = "Adjuvant")
h7 = Heatmap(patient_meta[,"E_I_D"], width = unit(0.5, "cm"), 
             height = unit(30, "cm"),
             show_heatmap_legend = TRUE,heatmap_legend_param = list(title = "E_I_D"),show_row_names = FALSE,
             column_labels = "E_I_D")

ht = grid.grabExpr(draw( h7 + h6 + h5 + h4 + h2  + h1))
grid.newpage()
pushViewport(viewport(angle = 270))
grid.draw(ht)

```

```{r barplot Tcytotoxic fraction per BlockID with clinical annotation, fig.height=15, fig.width=15, message=FALSE}
set.seed(426)
cur_df <- data.frame(E_I_D = sce$E_I_D,
                     BlockID = sce$BlockID,
                     celltype = sce$celltype,
                     Tcell_score = sce$Tcell_score_per_BlockID,
                     infiltration = sce$infiltration,
                     MM_location = sce$MM_location)

cur_df <- cur_df[which(cur_df$MM_location != ""),]

cur_df <- reshape2::dcast(cur_df,formula = "BlockID + Tcell_score  ~ celltype", fun.aggregate = length)
cur_df <- as.tibble(cur_df)


# calculate the fraction of Tcytotoxic cells
cur_df <- cur_df %>%
  mutate(Tcytotoxic_fraction = (Tcytotoxic/rowSums(cur_df[,-c(1,2)]))) 

matrixrownames <- as.character(cur_df$BlockID)

m <- as.matrix(cur_df$Tcytotoxic_fraction)
rownames(m) <- matrixrownames
m <- m[order(m[,1]),]

# construct color vector for Tcell score
count_vec <- as.vector(m)

ha <- rowAnnotation(Fraction_Tcyototoxic = anno_barplot(m,gp=gpar(fill="gray"),bar_width = 1,height = unit(30,"cm"),width = unit(15,"cm"),show_row_names =FALSE))

patient_meta <- as.data.table(metadata(sce))
patient_meta <- unique(patient_meta %>%
                         filter(BlockID %in% names(m)) %>%
                       select(BlockID ,Response_at_12m  ,Mutation , MM_location , Date_death , Adjuvant, Treatment_after_surgery, E_I_D))

patient_meta <- unique(patient_meta)
patient_meta <- patient_meta[which(patient_meta$Mutation != ""),]

mrownames <- patient_meta$BlockID 
patient_meta <- as.matrix(patient_meta)

rownames(patient_meta) <- mrownames
patient_meta <- patient_meta[names(m),]

# heatmap consisting of the patient_IDs. one color per patient
h1 = Heatmap(patient_meta[,"Date_death"], width = unit(0.5, "cm"), 
             height = unit(30, "cm"),
             show_heatmap_legend = TRUE,heatmap_legend_param = list(title = "Date death"),show_row_names = FALSE,
             column_labels = "Date death",right_annotation =  ha)
h2 = Heatmap(patient_meta[,"Mutation"], width = unit(0.5, "cm"), 
             height = unit(30, "cm"),
             show_heatmap_legend = TRUE,heatmap_legend_param = list(title = "Mutation"),show_row_names = FALSE,
             column_labels = "Mutation")
h4 = Heatmap(patient_meta[,"Treatment_after_surgery"], width = unit(0.5, "cm"), 
             height = unit(30, "cm"),
             show_heatmap_legend = TRUE,heatmap_legend_param = list(title = "Treatment_after_surgery"),show_row_names = FALSE,
             column_labels = "Treatment_after_surgery")
h5 = Heatmap(patient_meta[,"MM_location"], width = unit(0.5, "cm"), 
             height = unit(30, "cm"),
             show_heatmap_legend = TRUE,heatmap_legend_param = list(title = "MM_location"),show_row_names = FALSE,
             column_labels = "MM_location")
h6 = Heatmap(patient_meta[,"Adjuvant"], width = unit(0.5, "cm"), 
             height = unit(30, "cm"),
             show_heatmap_legend = TRUE,heatmap_legend_param = list(title = "Adjuvant"),show_row_names = FALSE,
             column_labels = "Adjuvant")
h7 = Heatmap(patient_meta[,"E_I_D"], width = unit(0.5, "cm"), 
             height = unit(30, "cm"),
             show_heatmap_legend = TRUE,heatmap_legend_param = list(title = "E_I_D"),show_row_names = FALSE,
             column_labels = "E_I_D")

ht = grid.grabExpr(draw( h7 + h6 + h5 + h4 + h2  + h1))
grid.newpage()
pushViewport(viewport(angle = 270))
grid.draw(ht)

```


```{r barplot Tcell score sorted with death for PatientID and interaction_score, fig.height=15, fig.width=15}
# add internal patient ID to sce
pat_ID <- metadata(sce)$Internal_pat_ID
sce$Internal_pat_ID <- pat_ID[sce$ImageNumber]

# import PatientID T cell score
Tscore_PatientID <- readRDS("~/bbvolume/Data/Melanoma/12plex/Tcell_score_per_PatientID.rds")
sce$Tcell_score_per_PatientID <- Tscore_PatientID[sce$Internal_pat_ID]

cur_df <- data.frame(E_I_D = sce$E_I_D,
                     PatientID = sce$Internal_pat_ID,
                     celltype = sce$celltype,
                     Tcell_score = sce$Tcell_score_per_PatientID)

cur_df <- reshape2::dcast(cur_df,formula = "PatientID + Tcell_score   ~ celltype")
cur_df <- as.tibble(cur_df)

# next we need the measured area per PatientID (sum of all images from one PatientID) to calculate the Tcytotoxic density. same measure as was used for the calculation of the Tcell_score_per_BlockID
PatientID_images <- data.frame(ImageNumber = sce$ImageNumber,
                           PatientID = sce$Internal_pat_ID)
PatientID_images <- unique(PatientID_images)
PatientID_vec <- PatientID_images$PatientID


PatientID_size <- data.frame(ImageNumber = 1:length(im_size),
                         image_size = im_size)
PatientID_size$PatientID <- PatientID_vec

PatientID_size <- PatientID_size %>%
  group_by(PatientID) %>%
  mutate(PatientIDsize = sum(image_size))

# remove unwanted information for merging
PatientID_size <- unique(PatientID_size %>%
  select(PatientID, PatientIDsize))
# add info to cur_df
cur_df <- left_join(x = cur_df,y = PatientID_size,"PatientID")

# calculate the density of Tcytotoxic cells
cur_df <- cur_df %>%
  mutate(Tcytotoxic_density = round(Tcytotoxic/PatientIDsize)) 

matrixrownames <- as.character(cur_df[which(cur_df$PatientID != ""),]$PatientID)

m <- (cur_df[which(cur_df$PatientID != ""),]$Tcytotoxic_density)
names(m) <- matrixrownames
m <- m[order(m)]

# construct color vector for Tcell score
count_vec <- as.vector(m)
length(count_vec[count_vec<40])

Tcell_score_col <- c(rep("red",length(count_vec[count_vec<=40])),
                         rep("orange",length(count_vec[which(count_vec <100 & count_vec > 40)])),
                         rep("lightgreen",length(count_vec[which(count_vec <400 & count_vec > 100)])),
                         rep("darkgreen",length(count_vec[count_vec>400])))

ha <- rowAnnotation(Tcells_per_mm2 = anno_barplot(m,gp=gpar(fill=Tcell_score_col),bar_width = 1,height = unit(30,"cm"),width = unit(15,"cm"),show_row_names =FALSE,ylab = "test"))



# now we sort the patient meta data
patient_meta <- as.data.table(metadata(sce))
patient_meta <- unique(patient_meta %>%
                         filter(Internal_pat_ID %in% names(m)) %>%
                       select(Internal_pat_ID, Date_death))

patient_meta <- unique(patient_meta)
patient_meta <- patient_meta[which(patient_meta$Internal_pat_ID  != ""),]

mrownames <- patient_meta$Internal_pat_ID 
patient_meta <- as.matrix(patient_meta)

rownames(patient_meta) <- mrownames
patient_meta <- patient_meta[names(m),]

# heatmap consisting of the patient_IDs. one color per patient
h1 = Heatmap(patient_meta[,"Date_death"], width = unit(0.5, "cm"), 
             height = unit(30, "cm"),
             show_heatmap_legend = TRUE,heatmap_legend_param = list(title = "Date death"),show_row_names = FALSE,
             column_labels = "Date death",right_annotation =  ha)


ht = grid.grabExpr(draw(h1))
grid.newpage()
pushViewport(viewport(angle = 270))
grid.draw(ht)

cur_df %>%
  filter(PatientID =="II")
cur_df %>%
  select(PatientID,Tcytotoxic_density)
```

```{r barplot Tcytotoxic fraction sorted with death for PatientID and interaction_score, fig.height=15, fig.width=15}
set.seed(562)
# import PatientID T cell score
Tscore_PatientID <- readRDS("~/bbvolume/Data/Melanoma/12plex/Tcell_score_per_PatientID.rds")
sce$Tcell_score_per_PatientID <- Tscore_PatientID[sce$Internal_pat_ID]

cur_df <- data.frame(E_I_D = sce$E_I_D,
                     PatientID = sce$Internal_pat_ID,
                     celltype = sce$celltype,
                     Tcell_score = sce$Tcell_score_per_PatientID)

cur_df <- reshape2::dcast(cur_df,formula = "PatientID + Tcell_score   ~ celltype")
cur_df <- as.tibble(cur_df)

# calculate the fraction of Tcytotoxic cells
cur_df <- cur_df %>%
  mutate(Tcytotoxic_fraction = (Tcytotoxic/rowSums(cur_df[,-c(1,2)]))) 

matrixrownames <- as.character(cur_df[which(cur_df$PatientID != ""),]$PatientID)

m <- (cur_df[which(cur_df$PatientID != ""),]$Tcytotoxic_fraction)
names(m) <- matrixrownames
m <- m[order(m)]

# construct color vector for Tcell score
count_vec <- as.vector(m)
length(count_vec[count_vec<40])


ha <- rowAnnotation(Tcytotoxic_fraction = anno_barplot(m,gp=gpar(fill="gray"),bar_width = 1,height = unit(30,"cm"),width = unit(15,"cm"),show_row_names =FALSE,ylab = "test"))



# now we sort the patient meta data
patient_meta <- data.frame(PatientID = sce$Internal_pat_ID,
                           Date_death = sce$Date_death)
patient_meta <- unique(patient_meta)
patient_meta <- patient_meta[which(patient_meta$PatientID != ""),]

mrownames <- patient_meta$PatientID 
patient_meta <- as.matrix(patient_meta)

rownames(patient_meta) <- mrownames
patient_meta <- patient_meta[names(m),]

# heatmap consisting of the patient_IDs. one color per patient
h1 = Heatmap(patient_meta[,"Date_death"], width = unit(0.5, "cm"), 
             height = unit(30, "cm"),
             show_heatmap_legend = TRUE,heatmap_legend_param = list(title = "Date death"),show_row_names = FALSE,
             column_labels = "Date death",right_annotation =  ha)


ht = grid.grabExpr(draw(h1))
grid.newpage()
pushViewport(viewport(angle = 270))
grid.draw(ht)
```

```{r median of Tcytotoxic fractions per patient for cohort split}
median(cur_df$Tcytotoxic_fraction)

cur_df$Tcyto_fraction_score <- "low"
cur_df[which(cur_df$Tcytotoxic_fraction > median(cur_df$Tcytotoxic_fraction)),]$Tcyto_fraction_score <- "high"

Tfrac_score <- cur_df$Tcyto_fraction_score
names(Tfrac_score) <- cur_df$PatientID

saveRDS(Tfrac_score,"~/bbvolume/Data/Melanoma/12plex/Tcyto_frac_score.rds")

```

