---
title: "07_chemokine_community_analysis"
author: "Tobias Hoch"
date: "2020-05-12"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Introduction

# Preparations

## Load libraries

First, we will load the libraries needed for this part of the analysis.

```{r load-libraries, message=FALSE}
library(SingleCellExperiment)
library(reshape2)
library(tidyverse)
library(dplyr)
library(data.table) 
library(fpc)
```

## Read the data

```{r load data}
sce = readRDS(file = "data/sce_RNA.rds")
```

# Community Analysis

## Community analysis - Chemokine-producing cells

```{r}
# Subset sce object to only contain chemokine producing cells
cur_sce <- sce[,sce$chemokine_cluster != 0]

# define fractions of chemokines present in community
cur_dt <- as.data.table(colData(cur_sce))
cur_dt <- cbind(cur_dt[,chemokine_cluster], cur_dt[,grepl(glob2rx("C*L*"),names(cur_dt)), with=FALSE])
colnames(cur_dt)[1] <- "chemokine_cluster"

cur_dt <- cur_dt %>%
  group_by(chemokine_cluster) %>%
  summarise_each(funs(sum))

# wide format of frequencies
freqs_wide <- t(scale(t(as.matrix(cur_dt[,-1])), center = FALSE, 
               scale = rowSums(cur_dt[,-1])))
freqs_wide <- cbind(cur_dt[,1],freqs_wide)

# long format of frequencies
freqs_long <- melt(as.data.table(freqs_wide), id = "chemokine_cluster")
colnames(freqs_long) <- c("chemokine_cluster", "celltype", "fraction")
```

## kmeans clustering to define similar chemokine clusters

```{r UMAP_chemokines_frequencies_celltype}
# clustering (based on chemokine abundance within a cluster)
estimate <- clusterboot(data=freqs_wide[,-1], B=100, 
                        bootmethod = c("boot"), 
                        distances = FALSE, 
                        krange = 2:20, 
                        clustermethod = kmeansCBI,
                        seed = 12345)

# add cluster ID to frequencies
freq_kmeans <- as.data.table(cbind(estimate$result$partition, freqs_wide[,1]))
colnames(freq_kmeans) <- c("kmean_cluster", "chemokine_cluster")
freq_kmeans$kmean_cluster <- factor(freq_kmeans$kmean_cluster, levels = 0:length(unique(freq_kmeans$kmean_cluster)))

cur_dt <- as.data.table(colData(sce))
cur_dt <- left_join(cur_dt, freq_kmeans)

# add community module to sce object
cur_dt[is.na(kmean_cluster), kmean_cluster := "0"]
colData(sce)$community_module <- cur_dt$kmean_cluster
```

## Save RDS

```{r save sce}
saveRDS(sce, file = "data/sce_rna.rds")
```
