---
title: "09_manual_scoring"
author: ""
date: "2020-11-05"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Preparations

```{r setup}
knitr::opts_chunk$set(echo = TRUE, message= FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

## Load libraries

```{r}
library(SingleCellExperiment)
library(dplyr)
```

## Read the data

```{r load data}
sce_protein <- readRDS(file = "data/sce_protein.rds")
sce_rna <- readRDS(file = "data/sce_RNA.rds")
manual_scoring <- read.csv("data/manual_infiltration_scoring.csv")
```

# Add manual scoring 

## Rename Scoring Levels

```{r}
# make manual scoring comparable to automatic
colnames(manual_scoring) <- c("Description", "manual_scoring")

manual_scoring[is.na(manual_scoring$manual_scoring),]$manual_scoring <- "no assessment possible"
manual_scoring[manual_scoring$manual_scoring == 1,]$manual_scoring <- "deserted"
manual_scoring[manual_scoring$manual_scoring == 2,]$manual_scoring <- "low-inflamed"
manual_scoring[manual_scoring$manual_scoring == 3,]$manual_scoring <- "high-inflamed"
manual_scoring[manual_scoring$manual_scoring == 4,]$manual_scoring <- "low-excluded"
manual_scoring[manual_scoring$manual_scoring == 5,]$manual_scoring <- "high-excluded"
manual_scoring[manual_scoring$Description %in% unique(sce_protein[,sce_protein$Location == "CTRL"]$Description),]$manual_scoring <- "control"

# remove G1 - split, control image anyway
manual_scoring <- manual_scoring[manual_scoring$Description != "G1 - split",]

# remove images that were excluded for analysis
manual_scoring <- manual_scoring[(manual_scoring$Description %in% unique(sce_rna$Description)) == TRUE,]
```

## Add manual scoring to both data sets and remove bad images

```{r}
cur_prot <- data.frame(colData(sce_protein))
cur_rna <- data.frame(colData(sce_rna))

cur_prot <- left_join(cur_prot, manual_scoring)
cur_rna <- left_join(cur_rna, manual_scoring)

sce_rna$manual_scoring <- cur_rna$manual_scoring
sce_protein$manual_scoring <- cur_prot$manual_scoring
```

## Save RDS

```{r}
saveRDS(sce_rna, "data/sce_RNA.rds")
saveRDS(sce_protein, "data/sce_protein.rds")
```
