---
title: "celltype correlation between protein and RNA dataset"
author: "daniels"
date: "21 08 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message= FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

# load packages

```{r load packages, message=FALSE}
sapply(list.files("~/bbvolume/Git/imcRtools/R/", full.names = TRUE), source)
sapply(list.files("~/bbvolume/Git/melanoma_publication/code/helper_functions/", full.names = TRUE), source)
library(SingleCellExperiment)
library(ggplot2)
library(reshape2)
library(cowplot)
library(tidyverse)
library(corrplot)
```


```{r load RNA and protein datasets}
sce_protein <- readRDS(file = "data/sce_protein.rds")

sce_RNA <- readRDS(file = "../../bbvolume/server_homes/thoch/Git/melanoma_publication/data/sce_RNA.rds")
```

## Generate one large table with data from both single cell experiments

```{r generate summary tables, eval=FALSE}
metadata_protein <- data.frame(metadata(sce_protein)[1:34],stringsAsFactors = FALSE)
metadata_RNA <- data.frame(metadata(sce_RNA)[1:34],stringsAsFactors = FALSE)

metadata_protein[order(metadata_protein$Description),]
metadata_RNA[order(metadata_RNA$Description),]

cur_df <- data.frame(ImageNumber = sce_protein$ImageNumber,
                     Tcell_score = sce_protein$Tcell_score,
                     infiltration = sce_protein$infiltration)
# this table now holds the image wise scores which were calculated from the protein dataset single cells.
cur_df <- unique(cur_df)

# add the table to the metadata_protein
metadata_protein <- merge(metadata_protein,cur_df,by = "ImageNumber")

```

## fraction celltype calculation

now we calculate per image the fraction of cell types or the count of specific cells

```{r RNA cellfractions, fig.height=12,fig.width=12}
cur_df_RNA <- as_tibble(data.frame(ImageNumber = sce_RNA$ImageNumber,
                                   celltype = sce_RNA$celltype,
                                   clustered_celltypes = sce_RNA$celltype_clustered,
                                   CCL2 = sce_RNA$CCL2,
                                   CCL4 = sce_RNA$CCL4,
                                   CCL8 = sce_RNA$CCL8,
                                   CCL18 = sce_RNA$CCL18,
                                   CCL19 = sce_RNA$CCL19,
                                   CCL22 = sce_RNA$CCL22,
                                   CXCL8 = sce_RNA$CXCL8,
                                   CXCL9 = sce_RNA$CXCL9,
                                   CXCL10 = sce_RNA$CXCL10,
                                   CXCL12 = sce_RNA$CXCL12,
                                   CXCL13 = sce_RNA$CXCL13))

celltypes_RNA <- cur_df_RNA %>%
  group_by(ImageNumber, celltype) %>%
  summarise(length(celltype)) %>%
  pivot_wider(names_from = celltype,values_from = "length(celltype)")

celltypes_RNA[is.na(celltypes_RNA)] = 0
colnames(celltypes_RNA) <- c("ImageNumber",paste0(colnames(celltypes_RNA[,-1]),"_RNA"))

# fractions calculation
cellfrac_RNA <- celltypes_RNA[,-1]/rowSums(celltypes_RNA[,-1])
cellfrac_RNA$ImageNumber <- celltypes_RNA$ImageNumber



clustered_celltypes_RNA <- cur_df_RNA %>%
    group_by(ImageNumber, clustered_celltypes) %>%
  summarise(length(clustered_celltypes)) %>%
  pivot_wider(names_from = clustered_celltypes,values_from = "length(clustered_celltypes)")

colnames(clustered_celltypes_RNA) <- c("ImageNumber",paste0(colnames(clustered_celltypes_RNA[,-1]),"_RNA"))

clustered_celltypes_RNA[is.na(clustered_celltypes_RNA)] = 0

# fractions calculation
clusterfrac_RNA <- clustered_celltypes_RNA[,-1]/rowSums(clustered_celltypes_RNA[,-1])
clusterfrac_RNA$ImageNumber <- clustered_celltypes_RNA$ImageNumber

Chemo_summary <- cur_df_RNA %>%
  group_by(ImageNumber) %>%
  select(! c(celltype,clustered_celltypes)) %>%
  summarize_all(sum)

chemo_frac <- Chemo_summary[,-1]/rowSums(celltypes_RNA[,-1])
chemo_frac$ImageNumber <- Chemo_summary$ImageNumber


# merge chemo_summary and celltype table
celltypes_RNA <- merge(celltypes_RNA,Chemo_summary,by="ImageNumber")

clustered_celltypes_RNA <- merge(clustered_celltypes_RNA,Chemo_summary,by="ImageNumber")
# replace NAs with 0

RNA_frac <- merge(cellfrac_RNA,clusterfrac_RNA,by="ImageNumber")
RNA_frac <- merge(RNA_frac,chemo_frac,by="ImageNumber")


RNA_celltypes_names <- colnames(celltypes_RNA[,-1])
RNA_clustered_celltypes_names <- colnames(clustered_celltypes_RNA[,-1])
chemokine_cells_names <- colnames(Chemo_summary[,-1])

RNA_frac$Description <- metadata_RNA$Description
```

```{r Protein cellfractions}
cur_df_protein <- as_tibble(data.frame(ImageNumber = sce_protein$ImageNumber,
                                   celltype = sce_protein$celltype,
                                   clustered_celltypes = sce_protein$celltype_clustered))

celltypes_protein <- cur_df_protein %>%
  group_by(ImageNumber, celltype) %>%
  summarise(length(celltype)) %>%
  pivot_wider(names_from = celltype,values_from = "length(celltype)")

colnames(celltypes_protein) <- c("ImageNumber",paste0(colnames(celltypes_protein[,-1]),"_protein"))


celltypes_protein[is.na(celltypes_protein)] = 0

# fractions calculation
cellfrac_protein <- celltypes_protein[,-1]/rowSums(celltypes_protein[,-1])
cellfrac_protein$ImageNumber <- celltypes_protein$ImageNumber

clustered_celltypes_protein <- cur_df_protein %>%
    group_by(ImageNumber, clustered_celltypes) %>%
  summarise(length(clustered_celltypes)) %>%
  pivot_wider(names_from = clustered_celltypes,values_from = "length(clustered_celltypes)")

colnames(clustered_celltypes_protein) <- c("ImageNumber",paste0(colnames(clustered_celltypes_protein[,-1]),"_protein"))


clustered_celltypes_protein[is.na(clustered_celltypes_protein)] = 0

# fractions calculation
clusterfrac_protein <- clustered_celltypes_protein[,-1]/rowSums(clustered_celltypes_protein[,-1])
clusterfrac_protein$ImageNumber <- clustered_celltypes_protein$ImageNumber

Protein_frac <- merge(cellfrac_protein,clusterfrac_protein,by="ImageNumber")

protein_celltypes_names <- colnames(celltypes_protein[,-1])
protein_clustered_celltypes_names <- colnames(clustered_celltypes_protein[,-1])


Protein_frac$Description <- metadata_protein$Description
```

```{r}
all_frac <- merge(Protein_frac[,-1],RNA_frac[,-1], by= "Description")

# find images that belong to control samples
ctrl_images <- unique(sce_protein[,sce_protein$Location == "CTRL"]$Description)

# remove control images from the data
all_frac <- all_frac %>%
  filter(! Description %in% ctrl_images)
```


```{r correlation of celltype fractions in RNA data,fig.height=12,fig.width=12}
M <-as.matrix(cellfrac_RNA %>%
  select(!ImageNumber))

corrplot(cor(M, method= "spearman"))
```

```{r correlation of celltype from RNA and protein,fig.height=12,fig.width=12}
M <-as.matrix(all_frac %>%
  select(!Description) %>%
    select(protein_celltypes_names,RNA_celltypes_names))

corrplot(cor(M, method= "spearman"))

cor(all_frac$Bcell_protein,all_frac$CXCL13, method = "pearson")
```

```{r correlation of celltype fractions in protein data}
M <-as.matrix(cellfrac_protein %>%
  select(!ImageNumber))

corrplot(cor(M, method= "spearman"))
```
```{r correlation of celltype fractions in protein data with chemokoines, fig.height=10, fig.width=10}
M <-as.matrix(all_frac %>%
  select(!Description) %>%
  select(protein_celltypes_names,chemokine_cells_names))

corrplot(cor(M, method= "pearson"))
ggplot(all_frac)+
  geom_point(aes(x=CXCL13,y=Bcell_protein),col="black")

cor(all_frac$CCL19,all_frac$Bcell_protein, method = "spearman")
cor(all_frac$CCL19,all_frac$Bcell_protein, method = "pearson")

cor.test(all_frac$CXCL13,all_frac$Bcell_protein)
ggplot(all_frac)+
  geom_point(aes(x=CCL22,y=Thelper_protein),col="green")+
  geom_point(aes(x=CXCL13,y=Bcell_protein),color="blue")+
  geom_point(aes(x=CXCL9,y=Tcytotoxic_protein),col="red")+
  geom_point(aes(x=CXCL12,y=pDC_protein),col="orange")

ggplot(all_frac)+
  geom_point(aes(x=CCL2,y=CCL4),col="green")+
  geom_point(aes(x=CXCL13,y=CXCL10),color="blue")+
  geom_point(aes(x=CXCL9,y=CXCL10),col="red")+
  geom_point(aes(x=CXCL10,y=CCL2),col="orange")

```

```{r protein clustered celltypes correlation with chemokines pearson, fig.height=25, fig.width=25}
M <-as.matrix(all_frac %>%
  select( !Description) %>%
  select(protein_clustered_celltypes_names,chemokine_cells_names))

corrplot(cor(M, method= "spearman"))
```



