---
title: "cell type summary clinical data for Tcell fraction score"
author: "Daniel"
date: "18 08 2020"
output: html_document
---

## here we compare the fractions of cell type clusters and marker expressions for T cell score

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message= FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

# load packages

```{r load packages, message=FALSE}
sapply(list.files("code/helper_functions/", full.names = TRUE), source)
library(LSD)
library(SingleCellExperiment)
library(ggplot2)
library(scater)
library(viridis)
library(igraph)
library(reshape2)
library(cowplot)
library(tidyverse)
library(spicyR)
library(pheatmap)
library(BiocParallel)
```


# load data

```{r load data}
sce = readRDS(file = "data/sce_protein.rds")

colour_vector <- readRDS("data/colour_vector.rds")
```

## generate data input format

```{r, eval=FALSE}

cellExp <- SegmentedCells(cellData = data.frame(celltype = as.factor(sce[,sce$ImageNumber  %in% c(1:10)]$celltype),
                                     ImageNumber = sce[,sce$ImageNumber  %in% c(1:10)]$ImageNumber,
                                     CellID = paste0("cell","_",sce[,sce$ImageNumber  %in% c(1:10)]$CellNumber),
                                     X = round(sce[,sce$ImageNumber  %in% c(1:10)]$Center_X),
                                     Y = round(sce[,sce$ImageNumber  %in% c(1:10)]$Center_Y)),
               cellProfiler = FALSE,
               cellTypeString = "celltype",imageIDString = "ImageNumber",spatialCoords = c("X","Y"))

lisaCurves <- lisa(cellExp, Rs = c(30),BPPARAM = BiocParallel::MulticoreParam())

lisaCurves[is.na(lisaCurves)] <- 0

kM <- kmeans(lisaCurves,50)
region(cellExp) <- paste('region',kM$cluster,sep = '_')

```

```{r,eval=FALSE}
ggplot(as.data.frame(cellSummary(cellExp)), aes(x,-y, colour = cellType)) + 
  geom_point(size = 0.5) + 
  facet_wrap(~imageID) + scale_color_manual(values = metadata(sce)$colour_vector$celltype)
```

```{r,eval=FALSE}
Tfrac_score <- sce[,sce$ImageNumber %in% c(1:10)]$T_frac_score_per_ImageNumber


for_heatmap_hot <- as_tibble(cbind(cellSummary(cellExp),region(cellExp),Tfrac_score)) %>%
  filter(Tfrac_score == "high") %>%
  group_by(imageID, region, cellType) %>%
  summarize(cellTypeCounts = n()) %>%
  mutate(cellTypeFraction = cellTypeCounts/sum(cellTypeCounts)) %>%
  select(-cellTypeCounts) %>%
  pivot_wider(names_from = c(imageID, region), values_from = cellTypeFraction, values_fill = 0) %>%
  as.data.frame()

rownames(for_heatmap_hot) <- for_heatmap_hot$cellType
for_heatmap_hot$cellType <- NULL

for_heatmap_med <- as_tibble(cbind(cellSummary(cellExp),region(cellExp),Tfrac_score)) %>%
  filter(Tfrac_score == "med") %>%
  group_by(imageID, region, cellType) %>%
  summarize(cellTypeCounts = n()) %>%
  mutate(cellTypeFraction = cellTypeCounts/sum(cellTypeCounts)) %>%
  select(-cellTypeCounts) %>%
  pivot_wider(names_from = c(imageID, region), values_from = cellTypeFraction, values_fill = 0) %>%
  as.data.frame()

rownames(for_heatmap_med) <- for_heatmap_med$cellType
for_heatmap_med$cellType <- NULL

for_heatmap_cold <- as_tibble(cbind(cellSummary(cellExp),region(cellExp),Tfrac_score)) %>%
  filter(Tfrac_score == "low") %>%
  group_by(imageID, region, cellType) %>%
  summarize(cellTypeCounts = n()) %>%
  mutate(cellTypeFraction = cellTypeCounts/sum(cellTypeCounts)) %>%
  select(-cellTypeCounts) %>%
  pivot_wider(names_from = c(imageID, region), values_from = cellTypeFraction, values_fill = 0) %>%
  as.data.frame()

rownames(for_heatmap_cold) <- for_heatmap_cold$cellType
for_heatmap_cold$cellType <- NULL

pheatmap(for_heatmap_hot, color = colorRampPalette(c("blue", "green", "yellow", "red"))(100),
         show_colnames = FALSE)
pheatmap(for_heatmap_med, color = colorRampPalette(c("blue", "green", "yellow", "red"))(100),
         show_colnames = FALSE)
pheatmap(for_heatmap_cold, color = colorRampPalette(c("blue", "green", "yellow", "red"))(100),
         show_colnames = FALSE)

```

```{r SpicyR enrichtment tests}
cellExp <- SegmentedCells(cellData = data.frame(celltype = as.factor(sce[,sce$ImageNumber  %in% c(1:10)]$celltype),
                                     ImageNumber = sce[,sce$ImageNumber  %in% c(1:10)]$ImageNumber,
                                     CellID = paste0("cell","_",sce[,sce$ImageNumber  %in% c(1:10)]$CellNumber),
                                     X = round(sce[,sce$ImageNumber  %in% c(1:10)]$Center_X),
                                     Y = round(sce[,sce$ImageNumber  %in% c(1:10)]$Center_Y)),
               cellProfiler = FALSE,
               cellTypeString = "celltype",imageIDString = "ImageNumber",spatialCoords = c("X","Y"))

cellExp2 <- SegmentedCells(cellData = data.frame(celltype = as.factor(sce$celltype_clustered),
                                     ImageNumber = sce$ImageNumber,
                                     CellID = paste0("cell","_",sce$CellNumber),
                                     X = round(sce$Center_X),
                                     Y = round(sce$Center_Y)),
               cellProfiler = FALSE,
               cellTypeString = "celltype",imageIDString = "ImageNumber",spatialCoords = c("X","Y"))


PhenoData <- unique(data.frame(imageID = as.factor(sce$ImageNumber),
                        MM_location = as.factor(sce$MM_location),
                        relapse = as.factor(sce$relapse),
                        death = as.factor(sce$Death),
                        Tfrac_score = as.factor(sce$T_frac_score_per_ImageNumber)))

imagePheno(cellExp2) <- PhenoData

SpicyTest <- spicy(cellExp2,
      condition = "MM_location",
      subject = "death")

topPairs(SpicyTest)  

paired_test <- spicy(spicy(cellExp,
      condition = "MM_location",
      subject = "death",
      from = "Tumor",
      to = "Tcytotoxic"))

```

