---
title: "Figure 2"
author: "Tobias Hoch and Daniel Schulz"
date: "2020-08-04"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Introduction
This script generates plots for Figure 2. Panel A was created manually.

# Preparation

```{r setup}
knitr::opts_chunk$set(echo = TRUE, message= FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

## Load libraries

```{r, message=F}
sapply(list.files("code/helper_functions", full.names = TRUE), source)
library(SingleCellExperiment)
library(ComplexHeatmap)
library(data.table)
library(dplyr)
library(janitor)
library(tidyr)
library(ggpmisc)
library(cowplot)
library(corrplot)
library(gridExtra)
library(ggalluvial)
library(ggbeeswarm)
library(ggpubr)
library(RColorBrewer)
library(colorRamps)
library(circlize)
library(forcats)
library(psych)
library(viridis)
library(ggpmisc)
```

## Load data

```{r}
sce_rna <- readRDS(file = "data/data_for_analysis/sce_RNA.rds")
sce_prot <- readRDS(file= "data/data_for_analysis/sce_protein.rds")

sce_rna <- sce_rna[,sce_rna$Location != "CTRL"]
sce_prot <- sce_prot[,sce_prot$Location != "CTRL"]
```

# Figure 2B

## UpSet plot with ComplexHeatmap - including CellType Annotation and Met Location

```{r Fig_2B_upset_plot, message=F, fig.width=8, fig.height=8, dev=c('pdf')}
cur_dt <- as.data.table(colData(sce_rna))

# combinations with more than 600 occurrences
targets <- metadata(sce_rna)$chemokines_morethan600_withcontrol
targets_no_control <- replace(targets, match(c("CXCL8", "CCL18"),targets), c("CCL18", "CXCL8"))

# remove control samples
cur_dt <- cur_dt[MM_location_simplified != "control",]

# extract chemokine columns
chemokines <- cbind(cur_dt[,c("ImageNumber", "MM_location_simplified", "celltype")], cur_dt[,grepl(glob2rx("C*L*"),names(cur_dt)), with = F])

# create combination matrix
m <- make_comb_mat(chemokines, top_n_sets = 11)

# filter based on combination size and combination degree
m <- m[comb_size(m) >= 600 & comb_degree(m) > 0]

# sort according to abundance
m <- m[order(-comb_size(m))]

# extract comb names
comb_names <- comb_name(m)

# count celltypes for each combination
celltypes <- data.table()
location <- data.table()

# summarize statistics for each combination (celltype fractions, location)
for (i in comb_names){
  # subset
  set <- chemokines[extract_comb(m, i)]
  
  # chemokines celltypes
  set1 <- set %>%
    group_by(celltype) %>%
    summarise(n=n()) %>%
    reshape2::dcast(.,i ~ celltype, value.var = "n")
  
  # chemokines by location
  set2 <- set %>%
    group_by(ImageNumber, MM_location_simplified) %>%
    summarise(n=n())
  
  # add images with no combinations to not distort median
  set2_add <- distinct(cur_dt[,c("ImageNumber", "MM_location_simplified")], ImageNumber, .keep_all = T)
  set2_add$n <- 0
  
  # subset to only contain images which are not already part of set2
  set2_add <- set2_add[!(ImageNumber %in% set2$ImageNumber),]
  
  set2 <- set2 %>%
    rbind(., set2_add) %>%
    group_by(MM_location_simplified) %>%
    mutate(median = median(n)) %>%
    distinct(MM_location_simplified, median) %>%
    reshape2::dcast(.,i ~ MM_location_simplified, value.var = "median")
  
  # add to data.frame
  celltypes <- rbind(celltypes, set1, fill = TRUE)
  location <- rbind(location, set2, fill = TRUE)
}

# replace NA
celltypes[is.na(celltypes)] <- 0
location[is.na(location)] <- 0

# properties of combination matrix
ss = set_size(m)
cs = comb_size(m)

# calculate fraction of chemokine combinations per patient
fraction_patient <- cur_dt %>%
  select(PatientID, expressor) %>%
  filter(expressor != "NA") %>%
  group_by(PatientID, expressor) %>%
  summarise(n=n()) %>%
  group_by(expressor) %>%
  mutate(fraction = n / sum(n)) %>%
  reshape2::dcast(expressor ~ PatientID, value.var = "fraction", fill = 0) %>%
  filter(expressor %in% targets) %>%
  reshape2::melt(id.vars=c("expressor"), variable.name="PatientID", value.name="fraction")

# how many chemokine combis are found in top10 patients?
fraction_patient <- fraction_patient %>%
  group_by(expressor) %>%
  slice_max(fraction, n=10) %>%
  summarise(top10=round(sum(fraction)*100,0))

# change row-order to match targets and remove expressor column (only keep fractions)
fraction_patient <- fraction_patient[match(targets,fraction_patient$expressor),-1]

# max fraction coming from one image per expressor
fraction_patient$top10 <- paste0(fraction_patient$top10, "%")

# create plot
ht = UpSet(m, 
           set_order = order(ss),
           comb_order = order(cs, decreasing = T),
           top_annotation = HeatmapAnnotation(
             "Number of\nExpressing Cells" = anno_barplot(celltypes[,-1], 
                                                          ylim = c(0, max(cs)*1.1),
                                                          border = FALSE, 
                                                          gp = gpar(fill = metadata(sce_rna)$colour_vectors$celltype[colnames(celltypes[,-1])]), 
                                                          axis_param = list(gp = gpar(fontsize=14)),
                                                          height = unit(7.5, "cm")), 
             annotation_name_side = "left", 
             annotation_name_rot = 0,
             annotation_name_gp = gpar(fontsize=14)),
           left_annotation = rowAnnotation(
             "Total Number of\nExpressing Cells" = anno_barplot(-ss, 
                                                                baseline = 0,
                                                                axis_param = list(
                                                                  at = c(0, -5000, -10000, -15000),
                                                                  labels = c(0, 5000, 10000, 15000),
                                                                  labels_rot = 0,
                                                                  gp = gpar(fontsize = 12)),
                                                                border = FALSE, 
                                                                gp = gpar(fill = "black"), 
                                                                width = unit(3, "cm"),
             ),
             set_name = anno_text(set_name(m), 
                                  location = 0.5, 
                                  gp = gpar(fontsize=14),
                                  just = "center",
                                  width = max_text_width(set_name(m)) + unit(4, "mm")),
             annotation_name_gp = gpar(fontsize=20)),
           right_annotation = NULL,
           show_row_names = FALSE,
           pt_size = unit(3, "mm"),
           lwd = 2,
           width = unit(8, "cm"),
           height = unit(8, "cm"),
           bottom_annotation = HeatmapAnnotation(Top10 = anno_text(t(fraction_patient),
                                                                 just = "center", location = 0.5,
                                                                 rot = 90,
                                                                 gp = gpar(fontsize=13))),
)

# draw heatmap
ht = draw(ht)

# add absolute numbers on top of barplot
od = column_order(ht)
row_od = row_order(ht)
decorate_annotation("Number of\nExpressing Cells", {
  grid.text(cs[od], x = seq_along(cs), y = unit(cs[od], "native") + unit(2, "pt"), 
            default.units = "native", just = c("left", "bottom"), 
            gp = gpar(fontsize = 13, col = "#404040"), rot = 45)
})
decorate_annotation("Total Number of\nExpressing Cells", {
  grid.text(ss[row_od], 
            x = unit(-ss[row_od], "native") + unit(-0.75, "cm"), 
            y = rev(seq_len(length(-ss))), 
            default.units = "native", rot = 0,
            gp = gpar(fontsize = 11))
})
```

## Legend for Figure

```{r Fig_2B_legend, dev=c('pdf'), fig.height=1, fig.width=2}
# legend for celltypes
lgd1 = Legend(labels = colnames(celltypes[,-1]), 
              title = "Celltypes", 
              legend_gp = gpar(fill = metadata(sce_rna)$colour_vectors$celltype[colnames(celltypes[,-1])],
                               fontsize = 18),
              nrow = 5)

draw(packLegend(lgd1,column_gap = unit(0.5, "cm"),
                max_height = unit(7, "cm")))
```

# Figure 2C

## Heatmap Marker Expression

```{r, Fig_2C_heatmap_marker_producing_cells, fig.width=12, fig.height=12, dev=("pdf")}
# add marker expression to cells
marker_expression <- data.frame(t(assay(sce_rna[rowData(sce_rna)$good_marker,], "asinh")))
marker_expression$cellID <- rownames(marker_expression)

# chemokine info
chemo <- data.frame(colData(sce_rna))[,c("cellID", "expressor", "celltype")] 

dat <- left_join(chemo, marker_expression, by = "cellID")
dat$cellID <- NULL

# aggregate data
dat_aggr <- dat %>%
  filter(expressor %in% colnames(colData(sce_rna))[grepl("CXCL|CCL", colnames(colData(sce_rna)))]) %>%
  group_by(celltype, expressor) %>%
  summarise_all(funs(mean))

# prepare matrix for heatmap
dat_aggr <- dat_aggr %>%
  arrange(celltype, expressor)

stats <- dat %>%
  filter(expressor %in% colnames(colData(sce_rna))[grepl("CXCL|CCL", colnames(colData(sce_rna)))]) %>%
  group_by(celltype, expressor) %>%
  summarise(n=n()) %>%
  filter(n>1000) %>%
  arrange(celltype, expressor)

dat_aggr <- dat_aggr %>%
  filter(paste0(celltype,expressor) %in% paste0(stats$celltype,stats$expressor))

# factorize expressor for column sorting in heatmap
dat_aggr$expressor <- factor(dat_aggr$expressor, levels = c("CCL4", "CCL18", "CCL22", "CXCL8", 
                                                            "CCL8", "CXCL9", "CXCL10", "CXCL13", "CCL2", "CXCL12", "CCL19"))
stats$expressor <- factor(stats$expressor, levels = c("CCL4", "CCL18", "CCL22", "CXCL8", 
                                                      "CCL8", "CXCL9", "CXCL10", "CXCL13", "CCL2", "CXCL12", "CCL19"))

dat_aggr <- dat_aggr %>%
  arrange(celltype, expressor)

stats <- stats %>%
  arrange(celltype, expressor)

# create and scale scale matrix
m <- as.matrix(t(dat_aggr[,-c(1:2)]))
m <- t(scale(t(m)))
colnames(m) <- dat_aggr$celltype

# create top annotations
ha <- HeatmapAnnotation("Chemokine" = dat_aggr$expressor,
                        "Cells" = anno_barplot(stats[,3],
                                               height = unit(1.5,"cm"),
                                               axis_param = list(gp = gpar(fontsize=14))),
                        "Cell Numbers" = anno_text(t(stats[,3]), 
                                                   which = "column", 
                                                   rot = 90, 
                                                   just = "center", 
                                                   location = 0.5,
                                                   gp = gpar(fontsize=14)),
                        col = list("Chemokine" = metadata(sce_rna)$colour_vectors$chemokine_single),
                        show_legend = FALSE,
                        annotation_name_gp = gpar(fontsize = 16))


# row_split for markers
rowData(sce_rna)$heatmap_relevance <- ""
rowData(sce_rna[rowData(sce_rna)$good_marker,])$heatmap_relevance <- "Lineage"
rowData(sce_rna[grepl("CXCL|CCL|DapB", rownames(sce_rna)),])$heatmap_relevance <- "Chemokine"
rowData(sce_rna[grepl("B2M|GLUT1|CD134|Lag3|CD163|cleavedPARP|pRB", rownames(sce_rna)),])$heatmap_relevance <- "Other"

# create heatmap
h <- Heatmap(m, name = "Scaled\nExpression",
             row_split = rowData(sce_rna[rowData(sce_rna)$good_marker,])$heatmap_relevance,
             cluster_columns = FALSE,
             show_column_names = FALSE,
             top_annotation = ha,
             show_heatmap_legend = FALSE,
             column_split = colnames(m),
             column_title_rot = 90,
             cluster_column_slices = TRUE,
             row_names_gp = gpar(fontsize = 13),
             column_title_gp = gpar(fontsize = 16),
             row_title_gp = gpar(fontsize = 16),
             col = colorRamp2(c(-3, 0, 3), c("blue", "white", "red")),
             height = unit(15, "cm"),
             width = unit(11,"cm"))

# draw heatmap
draw(h)
```

## Legend heatmap

```{r Fig_2C_legend_heatmap, dev="pdf", fig.height=2, fig.width=7}
lgd1 = color_mapping_legend(h@matrix_color_mapping, plot = FALSE, legend_direction = "horizontal", legend_width=unit(3,"cm"), at = c(-3:3))
lgd2 = color_mapping_legend(ha@anno_list$Chemokine@color_mapping, plot = FALSE, legend_direction = "horizontal", nrow = 4)

lgd_list = packLegend(lgd1,lgd2,direction = "horizontal", gap = unit(1,"cm"))
draw(lgd_list)
```

# Figure 2D

## Correlation of Chemokines with Celltypes (based on fractions)

```{r Fig_2D_pearson_correlation_chemokines_prot_data, fig.width=5, fig.height=7, dev=c('pdf')}
# define chemokines
targets <- metadata(sce_rna)$chemokines_morethan600_withcontrol

# top abundant chemokines
cur_rna <- data.frame(colData(sce_rna))

# protein data
cur_prot <- data.frame(colData(sce_prot))

# sum
rna_sum <- cur_rna %>%
  group_by(Description) %>%
  mutate(total_cells=n()) %>%
  ungroup() %>%
  group_by(Description, total_cells, expressor) %>%
  summarise(n=n()) %>%
  mutate(fraction=n/total_cells) %>%
  reshape2::dcast(Description ~ expressor, value.var = "fraction", fill = 0) 

# only keep highly abundant chemokines
rna_sum <- rna_sum[,c("Description", targets)]

prot_sum <- cur_prot %>%
  group_by(Description, celltype) %>%
  summarise(n = n()) %>%
  group_by(Description) %>%
  mutate(fraction = n/sum(n)) %>%
  reshape2::dcast(Description ~ celltype, value.var = "fraction", fill = 0)

# equal images
all(rna_sum$Description == prot_sum$Description)

# correlation
cor <- psych::corr.test(rna_sum[,-1], prot_sum[,-1], method = "pearson",adjust = "BH")

cur_dat <- as.data.frame(cor$r)
cur_dat$variable <- rownames(cur_dat)
dat_long <- reshape2::melt(cur_dat,id.vars="variable")
colnames(dat_long) <- c("chemokines","celltypes","correlation")

p_dat <- as_tibble(cor$p)
p_dat$variable <- rownames(cur_dat)
pdat_long <- reshape2::melt(p_dat,id.vars="variable")
colnames(pdat_long) <- c("chemokines","celltypes","p_adj")

dat_long$p_adj <- pdat_long$p_adj

dat_long <- dat_long %>%
  mutate(sig = ifelse(p_adj <= 0.001 & p_adj > 0.0001,0.001,p_adj))

dat_long <- dat_long %>%
  mutate(sig = case_when(p_adj <= 0.0001 ~ "< 0.0001",
                         p_adj <= 0.001 & p_adj > 0.0001 ~ "< 0.001",
                         p_adj <= 0.01 & p_adj > 0.001 ~ "< 0.01",
                         p_adj <= 0.1 & p_adj > 0.01 ~ "< 0.1",
                         p_adj >0.1 ~ "ns"))

# plot
a <- ggplot()+
  geom_tile(data = dat_long, aes(x = chemokines,y = celltypes,fill=sig),color = "gray",size = 0.1, alpha = 0.5)+
  scale_fill_manual(values = c("< 0.0001" = "darkgreen", "< 0.001" = "green3", "< 0.01"="green", "< 0.1" = "lightgray","ns" = "white"), name = "adj p-value" )+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90,hjust = 1,vjust = 0.5),
        text = element_text(size=18)) +
  geom_point(data = dat_long, aes(x=chemokines,y = celltypes),size=5.5, show.legend = FALSE) +
  geom_point(data = dat_long, aes(x=chemokines,y = celltypes, color=correlation),size= 5, shape=19) +
  scale_color_gradient2(low="blue",mid= "white", high="red", name = "Pearson correlation") + 
  xlab("Chemokines") +
  ylab("Cell Types")

a + theme(legend.position="none")
```

## Legend
```{r Fig_2D_legend, fig.width=3, fig.height=5, dev=c('pdf')}
legend <- get_legend(a)
as_ggplot(legend)
```

