---
title: "CXCL13_exhaustion_validation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(SingleCellExperiment)
library(imcRtools)
library(BiocParallel)
library(BiocNeighbors)
library(dittoSeq)
library(scater)
library(scales)
library(cowplot)
library(Hmisc)
set.seed(12345)
```

```{r}
sce <- read_steinbock(path = "data/full_data/exhaustion_stain",return_as = "sce",graphs_folder = NULL, regionprops_folder = NULL)
```
## add metadata

```{r}
assay(sce,"asinh") <- asinh(counts(sce))
colnames(sce) <- paste0(sce$sample_id,"_",sce$ObjectNumber)

# add information from dysfunction score and Description
imnames <- c("E5","H9","F9","L8","N10","F2","D8","E4","J4","G11","L4","O9")
names(imnames) <- unique(sce$sample_id)

sce$Description <- imnames[sce$sample_id]

sce$dysfunction_score <- "low_dysfunction"
sce[,sce$Description %in% c("E5","H9","F2","D8","J4","E4","G11","L4")]$dysfunction_score <- "high_dysfunction"
```

## UMAP

```{r}
# define normalized scaled counts
es <- assay(sce, "counts")

# here we define the clipping percentage. all values above the fraction are then put to 1
for (i in c(0.99)){
  qs <- rowQuantiles(es, probs = c(0.0, i))
  x <- (es - qs[, 1]) / (qs[, 2] - qs[, 1])
  x[x < 0] <- 0; x[x > 1] <- 1
  assay(sce, paste0("scaled_",i)) <- x
}

good_markers <- rownames(sce)[grep("DNA|Histone|Ecad",rownames(sce), invert = TRUE)]
Tcell_markers <- rownames(sce)[grep("CD3|CD4|CD7|CD8|TCF|Granzym|CD38|CD39|PD-1|Ki-67|CXCL13|ICOS|EOMES|Tim-3|GITR|LAG|CD57|FOXP3",rownames(sce))]
Tcell_markers <- Tcell_markers[which(Tcell_markers != "CD31-vWF")]

sce <- runUMAP(sce, exprs_values = "scaled_0.99", 
                     subset_row = good_markers, name = "UMAP_scaled",
               external_neighbors = TRUE, BNPARAM = AnnoyParam(),
               BPPARAM = MulticoreParam())

sce <- runUMAP(sce, exprs_values = "asinh", 
                     subset_row = good_markers, name = "UMAP_asinh",
               external_neighbors = TRUE, BNPARAM = AnnoyParam(),
               BPPARAM = MulticoreParam())



plotReducedDim(sce,dimred = "UMAP_scaled",colour_by = "Description")
plotReducedDim(sce,dimred = "UMAP_asinh",colour_by = "Description")
```
## Marker expression on UMAP_scaled

```{r, fig.height=18, fig.width=35}
p.list <- list()
for(i in good_markers){
  p.list[[i]] <- plotReducedDim(sce,dimred = "UMAP_scaled",colour_by = i, by_exprs_values = "scaled_0.99", 
                          point_size = 0.25, point_alpha = 1, shape_by = "dysfunction_score") +
    scale_colour_gradient2(name = i, low = "#2166ac", mid = "white", high = "#b2182b",
                           limits = c(0, 1), oob = squish,midpoint = 0.5)
}

plot_grid(plotlist = p.list, ncol = 6)
```
## Marker expression on UMAP_asinh

```{r, fig.height=18, fig.width=35}
p.list <- list()
for(i in good_markers){
  p.list[[i]] <- plotReducedDim(sce,dimred = "UMAP_asinh",colour_by = i, by_exprs_values = "asinh", 
                          point_size = 0.25, point_alpha = 1, shape_by = "dysfunction_score") +
    scale_colour_gradient2(name = i, low = "#2166ac", mid = "white", high = "#b2182b",
                           limits = c(0, 3), oob = squish,midpoint = 1.5)
}

plot_grid(plotlist = p.list, ncol = 6)
```

## CD8 expression per sample

```{r}
# define T cells
dittoRidgePlot(sce,var="CD3", group.by= "sample_id",assay = "asinh")
sce$celltype <- "other"
sce[,t(assay(sce,"asinh"))[,"CD3"] > 1.75]$celltype <- "Tcell"
sum(t(assay(sce,"asinh"))[,"CD3"] > 2)

dittoRidgePlot(sce,var="CD8a", group.by= "sample_id",assay = "asinh")
sce$CD8_Tcell <- ""
sce[,t(assay(sce,"asinh"))[,"CD8a"] > 1.5]$celltype <- "CD8_Tcell"
sum(t(assay(sce,"asinh"))[,"CD8a"] > 1.5)

plotReducedDim(sce,dimred = "UMAP_asinh",colour_by = "celltype",point_size =0.5)
plotReducedDim(sce,dimred = "UMAP_asinh",colour_by = "Description",point_size =0.5)
plotReducedDim(sce,dimred = "UMAP_asinh",colour_by = "CD8a", by_exprs_values = "asinh", 
                          point_size = 0.25, point_alpha = 1, shape_by = "dysfunction_score") +
    scale_colour_gradient2(name = "CD8", low = "#2166ac", mid = "white", high = "#b2182b",
                           limits = c(0, 4), oob = squish,midpoint = 2)
```


## UMAP of CD8 T cells asinh

```{r}
ex_markers <- c("CXCL13","PD-1","EOMES","CD39","GITR","Tim-3","LAG-3","CD38","Ki-67","GranzymeB")
cur_sce <- sce[,sce$celltype == "CD8_Tcell"]
cur_sce <- runUMAP(cur_sce, exprs_values = "asinh", 
                     subset_row = ex_markers, name = "UMAP_Tcells_asinh",
               external_neighbors = TRUE, BNPARAM = AnnoyParam(),
               BPPARAM = MulticoreParam())
plotReducedDim(cur_sce,dimred = "UMAP_Tcells_asinh",colour_by = "Description",point_size =0.5)
```

```{r}
plotReducedDim(cur_sce,dimred = "UMAP_Tcells_asinh",colour_by = "dysfunction_score",point_size =0.5)
```


## UMAP of T cells asinh for exhaustion markers

```{r, fig.height=7, fig.width=18}
ex_markers <- c("CXCL13","PD-1","EOMES","CD39","GITR","Tim-3","LAG-3","CD38","Ki-67","GranzymeB")
col_list <- list()
for(i in ex_markers){
  col_list[[i]][1] <- 0
  col_list[[i]][2] <- 3
}

col_list[["LAG-3"]][2] <- 1.5
col_list[["Tim-3"]][2] <- 4.5
col_list[["GITR"]][2] <- 2
col_list[["CD39"]][2] <- 3.5
col_list[["PD-1"]][2] <- 2
col_list[["EOMES"]][2] <- 2.5

p.list <- list()
for(i in ex_markers){
    p <- plotReducedDim(cur_sce,dimred = "UMAP_Tcells_asinh",colour_by = i, by_exprs_values = "asinh", 
                          point_size = 0.25, point_alpha = 1, shape_by = "dysfunction_score") +
    scale_colour_gradient(low="#2166ac", high="orange",name = i, oob=squish, limits = c(col_list[[i]][1], col_list[[i]][2]))
  p.list[[i]] <- p
}

plot_grid(plotlist = p.list, ncol = 5)

```

```{r}
plotReducedDim(cur_sce,dimred = "UMAP_Tcells_asinh",colour_by = "LAG-3", by_exprs_values = "asinh", 
                          point_size = 0.25, point_alpha = 1, shape_by = "dysfunction_score") +
    scale_colour_gradientn(colours = c("#2166ac","orange"),name = "LAG-3",
                           limits = c(0, 1.5))
```

## UMAP of CD8 T cells scaled

```{r}
cur_sce <- sce[,sce$celltype == "CD8_Tcell"]
cur_sce <- runUMAP(cur_sce, exprs_values = "scaled_0.99", 
                     subset_row = ex_markers, name = "UMAP_Tcells_scaled_0.99",
               external_neighbors = TRUE, BNPARAM = AnnoyParam(),
               BPPARAM = MulticoreParam())
plotReducedDim(cur_sce,dimred = "UMAP_Tcells_scaled_0.99",colour_by = "Description",point_size =0.5)
plotReducedDim(cur_sce,dimred = "UMAP_Tcells_scaled_0.99",colour_by = "dysfunction_score",point_size =0.5)
```

## UMAP of T cells scaled for exhaustion markers

```{r, fig.height=7, fig.width=18}
ex_markers <- c("CXCL13","PD-1","EOMES","CD39","GITR","Tim-3","LAG-3","CD38","Ki-67","GranzymeB")
p.list <- list()
for(i in ex_markers){
  p.list[[i]] <- plotReducedDim(cur_sce,dimred = "UMAP_Tcells_scaled_0.99",colour_by = i, by_exprs_values = "scaled_0.99", 
                          point_size = 0.25, point_alpha = 1, shape_by = "dysfunction_score") +
    scale_colour_gradientn(colours = c("#2166ac","orange"),name = i,
                           limits = c(0, 1), oob=squish)
}

plot_grid(plotlist = p.list, ncol = 5)
```

## Heatmap of CD8+ T cells only

```{r}
cur_sce <- sce[,sce$celltype %in% c("CD8_Tcell")]
dittoHeatmap(cur_sce,genes = ex_markers,annot.by = c("Description","dysfunction_score"),
             assay = "asinh",show_colnames = FALSE,scale= "none",
            cluster_rows = TRUE,cluster_cols = FALSE,order.by = "CXCL13",
            heatmap.colors = colorRampPalette(c("dark blue", "white", "dark red"))(100),
            breaks = seq(0,3, length.out = 101))
dittoHeatmap(cur_sce,genes = ex_markers,annot.by = c("Description","dysfunction_score"),
             assay = "asinh",show_colnames = FALSE,
            cluster_rows = TRUE,cluster_cols = FALSE,order.by = "CXCL13",
            heatmap.colors = colorRampPalette(c("dark blue", "white", "dark red"))(100),
            breaks = seq(-2,2, length.out = 101))
dittoHeatmap(cur_sce,genes = ex_markers,annot.by = c("Description","dysfunction_score"),
             assay = "asinh",show_colnames = FALSE,scale= "none",
            cluster_rows = TRUE,cluster_cols = FALSE,
            heatmap.colors = colorRampPalette(c("dark blue", "white", "dark red"))(100),
            breaks = seq(0,3, length.out = 101))

dittoHeatmap(cur_sce,genes = ex_markers,annot.by = c("Description","dysfunction_score"),
             assay = "scaled_0.99",show_colnames = FALSE,scale= "none",
            cluster_rows = TRUE,cluster_cols = FALSE,order.by = "CXCL13",
            heatmap.colors = colorRampPalette(c("dark blue", "white", "dark red"))(100),
            breaks = seq(0,0.8, length.out = 101))
dittoHeatmap(cur_sce,genes = ex_markers,annot.by = c("Description","dysfunction_score"),
             assay = "scaled_0.99",show_colnames = FALSE,scale= "none",
            cluster_rows = TRUE,cluster_cols = FALSE,
            heatmap.colors = colorRampPalette(c("dark blue", "white", "dark red"))(100),
            breaks = seq(0,1, length.out = 101))
```


## correlation analysis per image

```{r}
library(dplyr)
cor_dat <- matrix(nrow = 32, ncol = 12)
colnames(cor_dat) <- unique(sce$Description)
rownames(cor_dat) <- good_markers[which(good_markers != "CXCL13")]
for (i in unique(sce$Description)) {
  plot_dat <- as.matrix(t(assay(sce[,which(sce$Description == i & sce$celltype == "CD8_Tcell")],"asinh")))
  x <- cor(plot_dat)
  x <- x[good_markers[which(good_markers != "CXCL13")],"CXCL13"]
  cor_dat[,i] <- x
}



cor_dat <- reshape2::melt(cor_dat,id.vars = good_markers,value.name = "correlation",)

ggplot()+
  geom_tile(data = cor_dat, aes(x = Var2,y = Var1),color = "white",size = 0.1, alpha = 0.5)+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90,hjust = 1,vjust = 0.5))+
  geom_point(data = cor_dat, aes(x=Var2,y = Var1),size=2, show.legend = FALSE)+
  geom_point(data = cor_dat, aes(x=Var2,y = Var1, color=correlation),size= 2, shape=19)+
  scale_color_gradient2(low="blue",mid= "white", high="red", name = "Pearson correlation")


order_vec <- cor_dat %>%
  group_by(Var1) %>%
  mutate(median_cor = median(correlation)) %>%
  select(Var1,median_cor) %>%
  distinct() %>%
  arrange(desc(median_cor)) %>%
  pull(Var1)

names_ordered <- good_markers[which(good_markers != "CXCL13")]
factor(names_ordered,levels = order_vec)

ggplot(data = cor_dat,aes(x = factor(Var1,levels=order_vec),y=correlation))+
  geom_boxplot()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```
