---
title: "Supplementary Figure 8"
author: "Tobias Hoch and Daniel Schulz"
date: "2021-11-24"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Introduction
This script generates plots for Supplementary Figure 8.

# Preparations

## Load libraries

```{r load libraries}
sapply(list.files("code/helper_functions", full.names = TRUE), source)
library(data.table)
library(ggplot2)
library(broom)
library(dplyr)
library(tidyverse)
library(cowplot)
library(ggbeeswarm)
library(gridExtra)
library(SingleCellExperiment)
library(scater)
library(reshape2)
library(circlize)
library(rstatix)
library(corrplot)
library(ggpubr)
```

## Load Data

```{r}
# SCE object
sce_rna = readRDS(file = "data/data_for_analysis/sce_RNA.rds")
sce_rna <- sce_rna[,sce_rna$Location != "CTRL"]

targets <- metadata(sce_rna)$chemokines_morethan600_withcontrol
```

# Supp Figure 8A

## Patients per Location

```{r}
sce_rna$MM_location <- ifelse(sce_rna$MM_location %in% c("skin", "skin_undefine"), "skin_undefined", sce_rna$MM_location)

groups <- data.frame(colData(sce_rna)) %>%
  distinct(ImageNumber, .keep_all = T) %>%
  group_by(MM_location) %>%
  distinct(PatientID, .keep_all = T) %>%
  summarise(n=n()) %>%
  filter(n>=10) %>%
  arrange(-n)
```

## Boxplot/Barplot per Location for every chemokine combination

```{r}
fractions_per_image <- data.frame(colData(sce_rna)) %>%
  group_by(ImageNumber, MM_location, expressor, celltype) %>%
  summarise(n = n()) %>%
  group_by(ImageNumber) %>%
  mutate(fraction_per_image = n / sum(n)) %>%
  group_by(ImageNumber, expressor) %>%
  mutate(group_fraction = sum(fraction_per_image)) %>%
  ungroup() %>%
  filter(expressor %in% targets & MM_location %in% groups$MM_location)

# fraction of expressor cells per image 
fraction_expressor_per_image <- fractions_per_image %>%
  distinct(ImageNumber, MM_location, expressor, .keep_all = T) %>%
  reshape2::dcast(ImageNumber + MM_location ~ expressor, value.var = "group_fraction", fill = 0) %>%
  reshape2::melt(id.vars = c("ImageNumber", "MM_location"), variable.name = "expressor", 
                 value.name = "fraction_per_image")

# fraction of celltype expressing a certain combi per image
celltype_fractions <- fractions_per_image %>%
  distinct(ImageNumber, celltype, expressor, .keep_all = T) %>%
  reshape2::dcast(ImageNumber + MM_location + expressor ~ celltype, value.var = "fraction_per_image", fill = 0) %>%
  reshape2::melt(id.vars = c("ImageNumber", "MM_location", "expressor"), 
                 variable.name = "celltype", value.name = "fraction_per_image") %>%
  reshape2::dcast(ImageNumber + MM_location + celltype ~ expressor, value.var = "fraction_per_image", fill = 0) %>%
  reshape2::melt(id.vars = c("ImageNumber", "MM_location", "celltype"), 
                 variable.name = "expressor", value.name = "fraction_per_image") %>%
  group_by(MM_location, expressor, celltype) %>%
  summarise(sum_fraction = sum(fraction_per_image)) %>% # sum-up fractions over all images 
  group_by(MM_location, expressor) %>%
  mutate(proportions = sum_fraction / sum(sum_fraction)) # calculate proportions for each expressor
```

## Plot

```{r Supp_Fig_8A_expression_per_location, dev=c('pdf')}
# calculate signif of expressor-fractions per MM_location
fraction_expressor_per_image %>%
  group_by(expressor) %>%
  wilcox_test(fraction_per_image ~ MM_location) %>%
  adjust_pvalue(method = "BH") %>%
  add_significance("p.adj",cutpoints = c(0, 1e-04, 0.001, 0.01, 0.1, 1)) %>%
  arrange(p.adj)

plot_list <- list()
for(i in groups$MM_location) {
  a <- fraction_expressor_per_image %>%
    filter(MM_location == i) %>%  
    group_by(ImageNumber, expressor) %>%
    ggplot(., aes(y=as.factor(expressor), x=fraction_per_image)) + 
    geom_boxplot() + 
    geom_point(alpha=0.2) +
    theme_bw() +
    theme(axis.title.y = element_blank(),
          axis.text.y = element_text(hjust=0.5)) +
    xlab("Cell Fraction per Image") + 
    coord_cartesian(xlim = c(0,0.05))
  
  b <- celltype_fractions %>%
    filter(MM_location == i) %>%  
    ggplot(., aes(y=expressor, x=-proportions, fill=celltype)) + 
    geom_bar(stat = "identity") +
    theme_bw() +
    theme(axis.text.y = element_blank(),
          axis.title.y = element_blank()) +
    guides(fill=guide_legend(title = "Cell Type",nrow=2,byrow=TRUE)) +
    xlab("Producing Cell Types") +
          scale_fill_manual(values = unname(metadata(sce_rna)$colour_vectors$celltype),
                        breaks = names(metadata(sce_rna)$colour_vectors$celltype),
                        labels = names(metadata(sce_rna)$colour_vectors$celltype)) +
    scale_x_continuous(breaks=c(-1.00,-0.75,-0.5, -0.25, 0.00),
                     labels=c("100%", "75%", "50%", "25%", "0%"))
  
  leg <- get_legend(b)
  
  grid.arrange(b+theme(legend.position = "none"),a,nrow=1,
               widths = c(.75,1),
               top = i)
}
```


```{r Supp_Fig_2C_legend, dev=c('pdf'), fig.width=5, fig.height=2}
grid.arrange(leg)
```

# Supp Figure 8B

## Chemokines cross-correlation

```{r Supp_Fig_8B_correlation_chemokines, fig.width=9, fig.height=9, dev=c('pdf')}
# top abundant chemokines
cur_rna <- data.frame(colData(sce_rna))

# sum
rna_sum <- cur_rna %>%
  group_by(Description, expressor) %>%
  summarise(n = n()) %>%
  reshape2::dcast(Description ~ expressor, value.var = "n", fill = 0) 

# only keep highly abundant chemokines
rna_sum <- rna_sum[,colnames(rna_sum) %in% targets]

# correlation
cor <- cor(rna_sum, rna_sum, method = "pearson")

corrplot(cor, 
         order = "FPC",
         addCoef.col = "black",
         method = "circle",
         tl.col="black",
         tl.cex = 1.5)
```
