---
title: "Supplementary Figure 5"
author: "toobiwankenobi"
date: "2020-10-16"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Introduction
This script generates plots for Supplementary Figure 5 and computes statistical results for the manuscript.

# Preparations

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message= FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

## Load libraries

```{r load libraries}
sapply(list.files("code/helper_functions", full.names = TRUE), source)
library(SingleCellExperiment)
library(ggplot2)
library(gridExtra)
library(data.table)
library(tibble)
library(tidyr)
library(dplyr)
```

## Load Data

```{r}
sce_rna <- readRDS(file = "data/sce_RNA.rds")
targets <- metadata(sce_rna)$chemokines_morethan600_withcontrol
```

# Chemokine Expression by Different Clinical Parameters

## Mutational Status

```{r Fig_5A_mutational_status_normalized, dev=c('pdf'), fig.width=7, fig.height=8}
# subset sce_rna
group_size <- data.frame(colData(sce_rna)) %>%
  group_by(ImageNumber, Mutation) %>%
  distinct(ImageNumber, .keep_all = T) %>%
  group_by(Mutation) %>%
  summarise(n=n()) %>%
  filter(n>10 & Mutation != "")

sce_rna_sub <- sce_rna[,sce_rna$Mutation %in% group_size$Mutation]

plotCellCounts(sce = sce_rna_sub, 
                     sce_sub = sce_rna_sub[,which(sce_rna_sub$expressor %in% targets)],
                     cellID = "cellID",
                     colour_by = "expressor",
                     split_by = "Mutation",
                     imageID = "ImageNumber",
                     normalize = TRUE,
                     colour_vector = metadata(sce_rna)$colour_vectors$chemokine_combinations) + 
  guides(fill=guide_legend("Chemokine")) +
  theme(text = element_text(size=18))

t <- data.frame(colData(sce_rna_sub)) %>%
  group_by(ImageNumber, Mutation, chemokine) %>%
  summarise(n=n()) %>%
  group_by(ImageNumber) %>%
  mutate(fraction = n / sum(n)) %>%
  reshape2::dcast(ImageNumber + Mutation ~ chemokine, value.var = "fraction")

round(kruskal.test(x = t$`TRUE`, g = t$Mutation)$p.value,3)
```

## Mutational Status - Celltype 

```{r Fig_5B_mutational_status_proportions, dev=c('pdf'), fig.width=7, fig.height=8}
plotCellCounts(sce = sce_rna_sub[,which(sce_rna_sub$expressor %in% targets)],
               cellID = "cellID",
               colour_by = "celltype",
               split_by = "Mutation",
               imageID = "ImageNumber",
               proportion = TRUE,
               colour_vector = metadata(sce_rna)$colour_vectors$celltype) + 
  guides(fill=guide_legend("Location")) +
  theme(text = element_text(size=18))
```

## Cancer Stage

```{r Fig_5C_cancer_stage, dev=c('pdf'), fig.width=7, fig.height=8}
# subset sce_rna
group_size <- data.frame(colData(sce_rna)) %>%
  group_by(ImageNumber, Cancer_Stage) %>%
  distinct(ImageNumber, .keep_all = T) %>%
  group_by(Cancer_Stage) %>%
  summarise(n=n()) %>%
  filter(n>10 & Cancer_Stage != "")

sce_rna_sub <- sce_rna[,sce_rna$Cancer_Stage %in% group_size$Cancer_Stage]

plotCellCounts(sce = sce_rna_sub, 
                     sce_sub = sce_rna_sub[,which(sce_rna_sub$expressor %in% targets)],
                     cellID = "cellID",
                     colour_by = "expressor",
                     split_by = "Cancer_Stage",
                     imageID = "ImageNumber",
                     normalize = TRUE,
                     colour_vector = metadata(sce_rna)$colour_vectors$chemokine_combinations) + 
  guides(fill=guide_legend("Chemokine")) +
  theme(text = element_text(size=18))

t <- data.frame(colData(sce_rna_sub)) %>%
  group_by(ImageNumber, Cancer_Stage, chemokine) %>%
  summarise(n=n()) %>%
  group_by(ImageNumber) %>%
  mutate(fraction = n / sum(n)) %>%
  reshape2::dcast(ImageNumber + Cancer_Stage ~ chemokine, value.var = "fraction")

round(wilcox.test(t$`TRUE` ~ t$Cancer_Stage)$p.value,3)
```

## Age

```{r Fig_5D_age, dev=c('pdf'), fig.width=7, fig.height=8}
# subset sce_rna
group_size <- data.frame(colData(sce_rna)) %>%
  group_by(ImageNumber, Age) %>%
  distinct(ImageNumber, .keep_all = T) %>%
  group_by(Age) %>%
  summarise(n=n()) %>%
  filter(n>10 & Age != "")

sce_rna_sub <- sce_rna[,sce_rna$Age %in% group_size$Age]
sce_rna_sub[,sce_rna_sub$Age == "?60"]$Age <- "60+"

# relevel age factor
sce_rna_sub$Age <- factor(sce_rna_sub$Age, levels = c("<45", "45-59", "60+"))

plotCellCounts(sce = sce_rna_sub, 
                     sce_sub = sce_rna_sub[,which(sce_rna_sub$expressor %in% targets)],
                     cellID = "cellID",
                     colour_by = "expressor",
                     split_by = "Age",
                     imageID = "ImageNumber",
                     normalize = TRUE,
                     colour_vector = metadata(sce_rna)$colour_vectors$chemokine_combinations) + 
  guides(fill=guide_legend("Chemokine")) +
  theme(text = element_text(size=18))

t <- data.frame(colData(sce_rna_sub)) %>%
  group_by(ImageNumber, Age, chemokine) %>%
  summarise(n=n()) %>%
  group_by(ImageNumber) %>%
  mutate(fraction = n / sum(n)) %>%
  reshape2::dcast(ImageNumber + Age ~ chemokine, value.var = "fraction")

round(kruskal.test(x = t$`TRUE`, g = t$Age)$p.value,3)
```

## Gender

```{r Fig_5E_gender, dev=c('pdf'), fig.width=7, fig.height=8}
# subset sce_rna
group_size <- data.frame(colData(sce_rna)) %>%
  group_by(ImageNumber, Gender) %>%
  distinct(ImageNumber, .keep_all = T) %>%
  group_by(Gender) %>%
  summarise(n=n()) %>%
  filter(n>10 & Gender != "")

sce_rna_sub <- sce_rna[,sce_rna$Gender %in% group_size$Gender]

plotCellCounts(sce = sce_rna_sub, 
                     sce_sub = sce_rna_sub[,which(sce_rna_sub$expressor %in% targets)],
                     cellID = "cellID",
                     colour_by = "expressor",
                     split_by = "Gender",
                     imageID = "ImageNumber",
                     normalize = TRUE,
                     colour_vector = metadata(sce_rna)$colour_vectors$chemokine_combinations) + 
  guides(fill=guide_legend("Chemokine")) +
  theme(text = element_text(size=18))

t <- data.frame(colData(sce_rna_sub)) %>%
  group_by(ImageNumber, Gender, chemokine) %>%
  summarise(n=n()) %>%
  group_by(ImageNumber) %>%
  mutate(fraction = n / sum(n)) %>%
  reshape2::dcast(ImageNumber + Gender ~ chemokine, value.var = "fraction")

round(wilcox.test(t$`TRUE` ~ t$Gender)$p.value,3)
```
