---
title: "Supplementary Figure 2"
author: "Tobias Hoch and Daniel Schulz"
date: "2020-10-13"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Introduction
This script generates plots for Supplementary Figure 2. Panel B was created manually. 

# Preparations

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message= FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

## Load libraries

```{r load libraries}
sapply(list.files("code/helper_functions", full.names = TRUE), source)
library(data.table)
library(survival)
library(ggplot2)
library(broom)
library(dplyr)
library(RColorBrewer)
library(ggalluvial)
library(tidyverse)
library(cowplot)
library(ggbeeswarm)
library(gridExtra)
library(SingleCellExperiment)
library(scater)
library(cba)
library(ComplexHeatmap)
library(reshape2)
library(rms)
library(ggrepel)
library(circlize)
library(coxme)
library(rstatix)
library(corrplot)
library(ggpubr)
```

## Load Data

```{r}
# clinical data
dat <- read_csv("data/data_for_analysis/protein/clinical_data_protein.csv")

# SCE object
sce_prot = readRDS(file = "data/data_for_analysis/sce_protein.rds")
sce_rna = readRDS(file = "data/data_for_analysis/sce_RNA.rds")

sce_rna <- sce_rna[,sce_rna$Location != "CTRL"]
sce_prot <- sce_prot[,sce_prot$Location != "CTRL"]

clincial = read.csv(file = "data/data_for_analysis/protein/clinical_data_protein.csv")

targets <- metadata(sce_rna)$chemokines_morethan600_withcontrol
```

# Supp Figure 2A

## Fraction of Tumor Cells that express chemokines

```{r Supp_Fig_2A_tumor_cells_chemokine, dev=("pdf"), fig.width=9, fig.height=5}
cur_dat <- data.frame(colData(sce_rna))
cur_dat <- cur_dat %>%
  filter(celltype == "Tumor") %>%
  filter(Location != "CTRL")

cur_dat <- cur_dat[,c("ImageNumber", "Mutation", colnames(cur_dat)[grepl(glob2rx("C*L*"),names(cur_dat))])]

# colSums of Chemokines in Tumor Cells (Multiple Producer count more than once)
cur_dat <- cur_dat %>%
  group_by(ImageNumber, Mutation) %>%
  mutate(cells = n()) %>%
  group_by(ImageNumber, cells, Mutation) %>%
  summarise_each(funs(sum))

# compute fractions
cur_dat[,4:14] <- cur_dat[,4:14] / t(cur_dat$cells)

cur_dat <- cur_dat %>%
  filter(cells > 200) %>%
  reshape2::melt(id.vars=c("ImageNumber", "cells", "Mutation"), variable.name="chemokine", value.name="fraction")

ggplot(cur_dat,aes(x=fct_reorder(chemokine, fraction, .fun = median, .desc = TRUE), y=fraction+0.001)) + 
  geom_boxplot(alpha=.5) +
  geom_quasirandom(alpha=.2) +
  theme_bw() + 
  theme(text=element_text(size=16)) +
  ylab("Fraction of Expressing Tumor Cells\n(fraction + 0.001)") +
  xlab("") +
  scale_y_log10() +
  annotation_logticks(sides = "l") +
  geom_hline(yintercept = median(cur_dat$fraction+0.001), linetype = 2) 
```

## Mutation split by Location

```{r Supp_Fig_2D_mutation, dev=c('pdf'), fig.width=15, fig.height=9.5, eval=F}
# add control location to sce
sce_rna$MM_location_simplified2 <- sce_rna$MM_location_simplified
#sce_rna[,sce_rna$Location == "CTRL" & sce_rna$TissueType == "Skin"]$MM_location_simplified2 <- "control skin"
#sce_rna[,sce_rna$Location == "CTRL" & sce_rna$TissueType == "Lymphnode"]$MM_location_simplified2 <- "control LN"
#sce_rna[,sce_rna$Location == "CTRL" & sce_rna$TissueType == "PSO"]$MM_location_simplified2 <- "control psoriasis"

targets <- metadata(sce_rna)$chemokines_morethan600_withcontrol

# subset sce_rna
group_size <- data.frame(colData(sce_rna)) %>%
  group_by(ImageNumber, Mutation) %>%
  distinct(ImageNumber, .keep_all = T) %>%
  group_by(Mutation) %>%
  summarise(n=n()) %>%
  filter(n>10 & Mutation != "")

sce_rna_sub <- sce_rna[,sce_rna$Mutation %in% group_size$Mutation]

a <- plotCellCounts(sce = sce_rna_sub, 
                     sce_sub = sce_rna_sub[,which(sce_rna_sub$expressor %in% targets)],
                     cellID = "cellID",
                     colour_by = "expressor",
                     split_by = "Mutation",
                     imageID = "ImageNumber",
                     normalize = TRUE,
                    show_n = FALSE,
                     colour_vector = metadata(sce_rna)$colour_vectors$chemokine_combinations) + 
  guides(fill=guide_legend("Chemokine")) +
  theme(text = element_text(size=18))

b <- plotCellCounts(sce = sce_rna_sub[,which(sce_rna_sub$expressor %in% targets)],
                     cellID = "cellID",
                     colour_by = "celltype",
                     split_by = "Mutation",
                     imageID = "ImageNumber",
                     proportion = TRUE,
                    show_n = FALSE,
                     colour_vector = metadata(sce_rna)$colour_vectors$celltype) + 
  guides(fill=guide_legend("Cell Type")) +
  theme(text = element_text(size=18))

# fraction of chemokine-expressing cells per image
chemo <- data.frame(colData(sce_rna_sub)) %>%
  #filter(MM_location_simplified2 %in% c("skin_subcutaneous", "LN")) %>%
  group_by(ImageNumber, Mutation, chemokine, MM_location_simplified2) %>%
  summarise(n=n()) %>%
  group_by(ImageNumber) %>%
  mutate(fraction = n / sum(n)) %>%
  reshape2::dcast(ImageNumber + Mutation + MM_location_simplified2 ~ chemokine, value.var = "fraction")

median_expression <- median(chemo$`TRUE`)

stat.test <- chemo %>%
  wilcox_test(`TRUE` ~ Mutation) %>%
  adjust_pvalue(method="BH") %>%
  add_significance("p.adj",cutpoints = c(0, 1e-04, 0.001, 0.01, 0.1, 1)) %>%
  add_xy_position(x = "Mutation")

stat.test$y.position <- stat.test$y.position - 0.125

c <- ggplot(chemo, aes(x=Mutation, y=`TRUE`)) + 
  geom_boxplot(alpha=0.2, lwd=1.5) + 
  geom_quasirandom(aes(col=MM_location_simplified2), size=2, alpha=.8) +
  #geom_hline(yintercept = median_expression, linetype=2, size=2) + 
  stat_pvalue_manual(stat.test, label = "p.adj.signif", size = 7) + 
  xlab("") + 
  ylab("Fraction of Chemokine-Expressing Cells") +
  theme_bw() +
  theme(text = element_text(size=16),
        axis.text.x = element_text(angle=45, hjust=1, vjust=1)) +
  guides(col=guide_legend("Location")) + 
  coord_cartesian(ylim=c(0,0.35))

p <- grid.arrange(a,b, ncol=2, nrow=1)

grid.arrange(c,p,nrow=1, widths = c(0.35,0.65))

# MM_location for Mutations
data.frame(colData(sce_rna_sub)) %>%
  distinct(ImageNumber, .keep_all = T) %>%
  group_by(Mutation, MM_location_simplified) %>%
  summarise(n=n()) %>%
  group_by(Mutation) %>%
  mutate(percentage = n / sum(n) * 100)
```
