---
title: "Table_S4"
author: "Tobias Hoch"
date: "2021-11-22"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r}
library(SingleCellExperiment)
library(dplyr)
library(lubridate)
library(stringr)
```

## Load Clinical Data

```{r}
clinical_data_protein <- read.csv2("data/data_for_analysis/protein/clinical_data_protein.csv", sep = ",")
sce_prot = readRDS(file = "data/data_for_analysis/sce_protein.rds")
sce_prot <- sce_prot[,sce_prot$Location != "CTRL"]
```

## Information to add

```{r}
info <- as.data.frame(colData(sce_prot)) %>%
  distinct(BlockID, .keep_all = TRUE) %>%
  select(BlockID, MM_location_simplified)

clinical_data_protein <- left_join(clinical_data_protein, info)
```

# Information for Clinical Data Table

## BlockID level

```{r}
block_level <- clinical_data_protein %>%
  filter(Location != "CTRL") %>%
  distinct(BlockID, .keep_all = TRUE) %>%
  select(PatientID, BlockID, Age_range, Gender, Primary_melanoma_type, MM_location, Cancer_Stage, Mutation,
         Last_sys_treatment_before_surgery, Treatment_after_surgery, MM_location_simplified, Status_at_3m)

# total blocks
length(unique(block_level$BlockID))

# Sex
block_level %>%
  group_by(Gender) %>%
  summarise(n=n()) %>%
  mutate(percentage = round(n / sum(n) *100,2)) %>%
  as.data.frame()

# Age
block_level %>%
  group_by(Age_range) %>%
  summarise(n=n()) %>%
  mutate(percentage = round(n / sum(n) *100,2)) %>%
  as.data.frame()

# Primary Melanoma Type
block_level %>%
  group_by(Primary_melanoma_type) %>%
  summarise(n=n()) %>%
  mutate(percentage = n / sum(n) *100) %>%
  mutate(Primary_melanoma_type = ifelse(percentage > 5 | Primary_melanoma_type == "unknown", Primary_melanoma_type, "other")) %>%
  group_by(Primary_melanoma_type) %>%
  summarise(n=sum(n), percentage=round(sum(percentage),2)) %>%
  as.data.frame()

# Met Location
block_level %>%
  group_by(MM_location) %>%
  summarise(n=n()) %>%
  mutate(percentage = n / sum(n) *100) %>%
  mutate(MM_location = ifelse(percentage > 5, MM_location, "other")) %>%
  group_by(MM_location) %>%
  summarise(n=sum(n), percentage=round(sum(percentage),2)) %>%
  as.data.frame()

# Cancer Stage
block_level %>%
  group_by(Cancer_Stage) %>%
  summarise(n=n()) %>%
  mutate(percentage = round(n / sum(n) *100,2)) %>%
  as.data.frame()

# Mutation
block_level %>%
  group_by(Mutation) %>%
  summarise(n=n()) %>%
  mutate(percentage = n / sum(n) *100) %>%
  mutate(Mutation = ifelse(percentage > 5 | Mutation == "unknown", Mutation, "other")) %>%
  group_by(Mutation) %>%
  summarise(n=sum(n), percentage=sum(percentage))

# Systemic Treatment Before
block_level %>%
  group_by(Last_sys_treatment_before_surgery) %>%
  summarise(n=n()) %>%
  mutate(percentage = n / sum(n) *100) %>%
  mutate(Last_sys_treatment_before_surgery = ifelse(percentage > 5 | is.na(Last_sys_treatment_before_surgery) == T, Last_sys_treatment_before_surgery, "other")) %>%
  group_by(Last_sys_treatment_before_surgery) %>%
  summarise(n=sum(n)) %>%
  mutate(percentage = round(n / sum(n) *100,2)) %>%
  as.data.frame()

# Systemic Treatment After
block_level %>%
  mutate(Last_sys_treatment_before_surgery = ifelse(is.na(Last_sys_treatment_before_surgery), 
                                                    "unknown", Last_sys_treatment_before_surgery)) %>%
  mutate(Treatment_after_surgery = ifelse(is.na(Treatment_after_surgery), 
                                                    "unknown", Treatment_after_surgery)) %>%
  mutate(treatmentGroup_before = ifelse(Last_sys_treatment_before_surgery == "untreated", 
         "Naive", "Pre-Treated")) %>%
  mutate(treatmentGroup_before = ifelse(Last_sys_treatment_before_surgery == "unknown", 
         "Unknown", treatmentGroup_before)) %>%
  mutate(treatmentGroups = paste(treatmentGroup_before, Treatment_after_surgery, sep = "_")) %>%
  group_by(treatmentGroup_before, treatmentGroups) %>%
  summarise(n=n()) %>%
  ungroup() %>%
  mutate(percentage = n / sum(n) *100) %>%
  mutate(treatmentGroups = ifelse(percentage > 5, treatmentGroups, paste(treatmentGroup_before, "other", sep = "_"))) %>%
  group_by(treatmentGroups) %>%
  summarise(n=sum(n), percentage=round(sum(percentage),2)) %>%
  as.data.frame()

# Response Information 3M after 
block_level %>%
  group_by(Status_at_3m) %>%
  summarise(n=n()) %>%
  mutate(percentage = n / sum(n) *100) %>%
  mutate(Status_at_3m = ifelse(percentage > 5, Status_at_3m, "other")) %>%
  group_by(Status_at_3m) %>%
  summarise(n=sum(n), percentage=round(sum(percentage),2)) %>%
  as.data.frame()
```

## Patient level

## Which paramters are unique for patients (not multiple levels per patient)

```{r}
unique_variables <- block_level %>%
  reshape2::melt(id.vars="PatientID", variable.name="Variable", value.name="Value") %>%
  group_by(PatientID, Variable) %>%
  distinct(Value, .keep_all = T) %>%
  summarise(n=n())

multiple_levels <- unique(as.character(unique_variables[unique_variables$n > 1,]$Variable))
all_variables <- unique(as.character(unique_variables$Variable))
unique_variables <- setdiff(all_variables, multiple_levels)
``` 

```{r}
patient_level <- block_level %>%
  distinct(PatientID, Age_range, Gender, Primary_melanoma_type, Cancer_Stage)

# total blocks
length(unique(patient_level$PatientID))

# Sex
patient_level %>%
  group_by(Gender) %>%
  summarise(n=n()) %>%
  mutate(percentage = round(n / sum(n) *100,2)) %>%
  as.data.frame()

# Age
patient_level %>%
  group_by(Age_range) %>%
  summarise(n=n()) %>%
  mutate(percentage = round(n / sum(n) *100,2)) %>%
  as.data.frame()

# Primary Melanoma Type
patient_level %>%
  group_by(Primary_melanoma_type) %>%
  summarise(n=n()) %>%
  mutate(percentage = n / sum(n) *100) %>%
  mutate(Primary_melanoma_type = ifelse(percentage > 5, Primary_melanoma_type, "other")) %>%
  group_by(Primary_melanoma_type) %>%
  summarise(n=sum(n), percentage=round(sum(percentage),2)) %>%
  as.data.frame()

# Cancer Stage
patient_level %>%
  group_by(Cancer_Stage) %>%
  summarise(n=n()) %>%
  mutate(percentage = round(n / sum(n) *100,2)) %>%
  as.data.frame()
```

## Whole Data Table as CSV

```{r}
# join with T cell Score, B cell Score, Dysfunction Score
scores <- as.data.frame(colData(sce_prot)) %>%
  distinct(Description, .keep_all = T) %>%
  select(Description, Tcell_density_score_image, bcell_patch_score, dysfunction_score)

clinicalDat <- left_join(scores, clinical_data_protein)

clinicalDat$IHC_T_score <- NULL
clinicalDat$Age_range <- ifelse(clinicalDat$Age_range =="≥60", ">=60", clinicalDat$Age_range)

# correct clinicalDat$Last_prev_therapy
clinicalDat$Last_prev_therapy <- str_replace_all(clinicalDat$Last_prev_therapy, "-", ".")
clinicalDat$Last_prev_therapy <- format(as.Date(my(clinicalDat$Last_prev_therapy)),"01-%b-20%y")

write.csv2(clinicalDat, "data/data_for_analysis/Table_S4.csv", row.names = FALSE)
```

