---
title: "clinical data summary"
author: "daniels"
date: "9 4 2020"
output:
  html_document: 
    self_contained: no
  pdf_document: default
---

# Introduction
This script gives an overview over the clinical data and generates statistics used in the manuscript. 

# Preparations

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message= FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

## Load libraries

```{r load libraries}
sapply(list.files("code/helper_functions", full.names = TRUE), source)
library(data.table)
library(dplyr)
library(SingleCellExperiment)
```

## Load Data

```{r}
# clinical data
dat <- read_csv("data/protein/clinical_data_protein.csv")

# SCE object
sce_protein = readRDS(file = "data/sce_protein.rds")
sce_rna = readRDS(file = "data/sce_RNA.rds")
```

# Statistics

## Number of Samples and Patients

```{r}
# Number of Samples without control samples
data.frame(colData(sce_protein)) %>%
  filter(Location != "CTRL") %>%
  distinct(Description) %>%
  summarise(n=n())

# Number of Patients
data.frame(colData(sce_protein)) %>%
  filter(Location != "CTRL") %>%
  distinct(PatientID) %>%
  summarise(n=n())
```

## Number of Celltypes

```{r}
# Protein data
data.frame(colData(sce_protein)) %>%
  filter(Location != "CTRL") %>%
  group_by(celltype) %>%
  summarise(n=n())

# RNA data
data.frame(colData(sce_rna)) %>%
  filter(Location != "CTRL") %>%
  group_by(celltype) %>%
  summarise(n=n())
```

## Number of Chemokine Expressing Cells

```{r}
# Percentage of Chemokine Producing Cells
data.frame(colData(sce_rna)) %>%
  filter(Location != "CTRL") %>%
  group_by(chemokine) %>%
  summarise(n=n()) %>%
  mutate(percentage = round((n / sum(n)) *100,1))

# Chemokines by Celltype
data.frame(colData(sce_rna)) %>%
  filter(Location != "CTRL") %>%
  filter(chemokine == 1) %>%
  group_by(celltype) %>%
  summarise(n=n()) %>%
  mutate(percentage = round((n / sum(n)) *100,1))
```

## Chemokine Expression in Tumor Cells

```{r}
# CXCL10 in Tumor cells
data.frame(colData(sce_rna)) %>%
  filter(Location != "CTRL") %>%
  filter(CXCL10 == 1) %>%
  group_by(celltype) %>%
  summarise(n=n()) %>%
  mutate(percentage = round((n / sum(n)) *100,1))

# CCL2 in Tumor cells
data.frame(colData(sce_rna)) %>%
  filter(Location != "CTRL") %>%
  filter(CCL2 == 1) %>%
  group_by(celltype) %>%
  summarise(n=n()) %>%
  mutate(percentage = round((n / sum(n)) *100,1))

# CXCL8 in Tumor cells
data.frame(colData(sce_rna)) %>%
  filter(Location != "CTRL") %>%
  filter(CXCL8 == 1) %>%
  group_by(celltype) %>%
  summarise(n=n()) %>%
  mutate(percentage = round((n / sum(n)) *100,1))

# CXCL12 in Tumor cells
data.frame(colData(sce_rna)) %>%
  filter(Location != "CTRL") %>%
  filter(CXCL12 == 1) %>%
  group_by(celltype) %>%
  summarise(n=n()) %>%
  mutate(percentage = round((n / sum(n)) *100,1))
```

## Chemokine Expression in Locations

```{r}
# overall chemokine expression
data.frame(colData(sce_rna)) %>%
  filter(Location == "CTRL") %>%
  group_by(chemokine, TissueType) %>%
  summarise(n=n()) %>%
  reshape2::dcast(TissueType ~ chemokine, value.var = "n", fill = 0) %>%
  mutate(percentage_expressing = round(`TRUE` / (`FALSE`+`TRUE`) * 100,1))

# CXCL13 expression in control samples
data.frame(colData(sce_rna)) %>%
  filter(Location == "CTRL") %>%
  group_by(CXCL13, TissueType) %>%
  summarise(n=n()) %>%
  reshape2::dcast(TissueType ~ CXCL13, value.var = "n", fill = 0) %>%
  mutate(percentage_expressing = round(`1` / (`0`+`1`) * 100,1))

# CXCL13 expression in tumor samples
data.frame(colData(sce_rna)) %>%
  filter(Location != "CTRL") %>%
  group_by(CXCL13, MM_location) %>%
  summarise(n=n()) %>%
  reshape2::dcast(MM_location ~ CXCL13, value.var = "n", fill = 0) %>%
  mutate(percentage_expressing = round(`1` / (`0`+`1`) * 100,1))

# CXCL10 expression in control samples
data.frame(colData(sce_rna)) %>%
  filter(Location == "CTRL") %>%
  group_by(CXCL10, TissueType) %>%
  summarise(n=n()) %>%
  reshape2::dcast(TissueType ~ CXCL10, value.var = "n", fill = 0) %>%
  mutate(percentage_expressing = round(`1` / (`0`+`1`) * 100,1))

# CXCL10 expression in tumor samples
data.frame(colData(sce_rna)) %>%
  filter(Location != "CTRL") %>%
  group_by(CXCL10, MM_location) %>%
  summarise(n=n()) %>%
  reshape2::dcast(MM_location ~ CXCL10, value.var = "n", fill = 0) %>%
  mutate(percentage_expressing = round(`1` / (`0`+`1`) * 100,1))
```

