---
title: "XX_RNA_CXCL13_CD8_analysis"
author: "toobiwankenobi"
date: "2020-09-02"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Introduction

# Preparations

## Load libraries

First, we will load the libraries needed for this part of the analysis.

```{r load-libraries, message=FALSE}
library(SingleCellExperiment)
library(dtplyr)
library(ggplot2)
```

## Read the data

```{r load data}
sce_rna = readRDS(file = "data/sce_RNA.rds")
sce_prot = readRDS(file = "data/sce_protein.rds")
```

# 

## Abundance of CXCL13+CD8+ cells

```{r}
cur_rna <- sce_rna[,sce_rna$celltype == "Tcytotoxic"]
cur_prot <- sce_prot[,sce_prot$celltype %in% c("Bcell", "BnTcell")]

cur_rna <- data.frame(colData(cur_rna)) %>%
  mutate(celltype = paste(celltype,CXCL13, sep = "_")) %>%
  group_by(Description,celltype) %>%
  summarise(n=n()) %>%
  reshape2::dcast(Description ~ celltype, value.var = "n", fill=0)

cur_prot <- data.frame(colData(cur_prot)) %>%
  group_by(Description,celltype) %>%
  summarise(n=n()) %>%
  reshape2::dcast(Description ~ celltype, value.var = "n", fill=0)

summary <- left_join(cur_rna, cur_prot)

summary[is.na(summary)] <- 0

ggplot(data=summary, aes(x=log10(Tcytotoxic_0), y=log10(Bcell + BnTcell))) + 
  geom_point() +
  geom_smooth(method = "lm")
```

