---
title: "XX_RNA_chemokine_expression_distance"
author: "toobiwankenobi"
date: "2020-09-11"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Introduction

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message= FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

# Preparations

## Load packages and helper functions

```{r message=F}
sapply(list.files("code/helper_functions", full.names = TRUE), source)
library(SingleCellExperiment)
library(ggplot2)
library(reshape2)
library(cowplot)
library(dplyr)
library(sf)
library(gridExtra)
```

## Load data

```{r load data}
sce = readRDS(file = "data/sce_rna.rds")
```

# Clusters/Communities - General

## Calculate Distance to Chemokine Cluster Center for each cluster cell

```{r Distance measurement}
cur_sce <- data.frame(colData(sce))
for(i in names(cur_sce[,grepl(glob2rx("C*L*"),names(cur_sce))])) {
  # distance measure
  sce <- calculateDistance(sce,
                    'cellID', 
                    'Center_X', 'Center_Y', 
                    'ImageNumber',
                    cluster = paste(tolower(i), "only_clust", sep = ""),
                    output_colname = paste("distance_to_", tolower(i), sep = ""))
} 

```

## Chemokine Expression Strenght as a Function of Distance-to-Center

```{r chemokine_expression_distance, fig.width=10, fig.height=8}
plot_list <- list()

for(i in rownames(sce[grepl(glob2rx("*C*L*"),rownames(sce)),])) {
  name <- strsplit(i, "_")
  name <- tolower(name[[1]][2])
  clust_name <- (paste(name, "only_clust", sep = ""))
  dist_name <- paste("distance_to_",name,sep = "")
  
  # subset sce
  cur_sce <- sce[,!(is.na(colData(sce)[,c(dist_name)]))]
  
  exprs <- data.frame(assay(cur_sce,"scaled_asinh")[i,])
  exprs  <- cbind(exprs, colData(cur_sce)[,c(dist_name, clust_name)])
  colnames(exprs)[1:2] <- c("scaled_asinh", "distance")
  
  # remove cluster of single-cells
  exprs <- exprs[exprs[,"distance"] != 0,]
  
  p <- ggplot(data = exprs, aes(x=log10(distance), y=scaled_asinh)) + 
    geom_point() + 
    geom_density_2d(col="blue", size=1) +
    xlab("Distance-to-Center of Cluster (log10)") + 
    ylab(paste("Scaled Expression of ", name, sep = ""))
  
  plot_list[[i]] <-  p
}

n <- length(plot_list)
nCol <- floor(sqrt(n))
do.call("grid.arrange", c(plot_list, ncol=nCol))
```

## Chemokine Expression Strenght as a Function of Cluster Size

```{r chemokine_expression_cluster_size, fig.width=10, fig.height=8}
plot_list <- list()

for(i in rownames(sce[grepl(glob2rx("*C*L*"),rownames(sce)),])) {
  name <- strsplit(i, "_")
  name <- tolower(name[[1]][2])
  clust_name <- (paste(name, "only_clust", sep = ""))
  dist_name <- (paste("distance_to_",name, sep = ""))

  # calculate cluster size
  clust_size <- data.frame(colData(sce)) %>%
    group_by_at(clust_name) %>%
    summarise(clust_size = n()) 
  
  # subset sce
  cur_sce <- sce[,!(is.na(colData(sce)[,c(dist_name)]))]
  
  exprs <- data.frame(assay(cur_sce,"scaled_asinh")[i,])
  exprs  <- cbind(exprs, colData(cur_sce)[,c(clust_name)])
  colnames(exprs)[1:2] <- c("scaled_asinh", clust_name)
  
  # combine cluster size and expression table
  exprs <- left_join(exprs, clust_size)
  
  p <- ggplot(data = exprs, aes(x=log10(clust_size), y=scaled_asinh)) + 
    geom_point() + 
    geom_smooth(method = "lm") +
    xlim(0,3) +
    xlab("Cluster Size (log10)") + 
    ylab(paste("Scaled Expression of ", name, sep = ""))
  
  plot_list[[i]] <-  p
}

n <- length(plot_list)
nCol <- floor(sqrt(n))
do.call("grid.arrange", c(plot_list, ncol=nCol))
```

